// Code generated by hertz generator.

package health

import (
	"context"

	healthmodel "github.com/PolarishT/sales-agent/biz/model/health"
	httpapi "github.com/PolarishT/sales-agent/internal/http"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Live reports whether the process can serve HTTP requests.
func Live(_ context.Context, ctx *app.RequestContext) {
	ctx.JSON(consts.StatusOK, &healthmodel.HealthResponse{Status: "ok", Code: "LIVE"})
}

// Ready reports whether the runtime database dependency is reachable.
func Ready(ctx context.Context, requestContext *app.RequestContext) {
	dependencies, ok := httpapi.DependenciesFrom(requestContext)
	if !ok || dependencies.HealthChecker == nil {
		httpapi.WriteError(requestContext, consts.StatusServiceUnavailable, "unavailable", "DATABASE_UNAVAILABLE", "数据库暂不可用")
		return
	}

	checkContext, cancel := context.WithTimeout(ctx, dependencies.ReadinessTimeout)
	defer cancel()
	if err := dependencies.HealthChecker.Ping(checkContext); err != nil {
		httpapi.WriteError(requestContext, consts.StatusServiceUnavailable, "unavailable", "DATABASE_UNAVAILABLE", "数据库暂不可用")
		return
	}

	requestContext.JSON(consts.StatusOK, &healthmodel.HealthResponse{Status: "ok", Code: "READY"})
}
