// Code generated by hertz generator.

package main

import "github.com/cloudwego/hertz/pkg/app/server"

// customizedRegister registers routes that cannot be expressed by IDL.
func customizedRegister(_ *server.Hertz) {}
