// Code generated by ent, DO NOT EDIT.

package ragdocumentversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ragdocumentversion type in the database.
	Label = "rag_document_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIngestionID holds the string denoting the ingestion_id field in the database.
	FieldIngestionID = "ingestion_id"
	// FieldDocumentID holds the string denoting the document_id field in the database.
	FieldDocumentID = "document_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldFileName holds the string denoting the file_name field in the database.
	FieldFileName = "file_name"
	// FieldContentHash holds the string denoting the content_hash field in the database.
	FieldContentHash = "content_hash"
	// FieldOriginalMarkdown holds the string denoting the original_markdown field in the database.
	FieldOriginalMarkdown = "original_markdown"
	// FieldSourceBytes holds the string denoting the source_bytes field in the database.
	FieldSourceBytes = "source_bytes"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStage holds the string denoting the stage field in the database.
	FieldStage = "stage"
	// FieldChunkCount holds the string denoting the chunk_count field in the database.
	FieldChunkCount = "chunk_count"
	// FieldEmbeddedChunkCount holds the string denoting the embedded_chunk_count field in the database.
	FieldEmbeddedChunkCount = "embedded_chunk_count"
	// FieldFailureCode holds the string denoting the failure_code field in the database.
	FieldFailureCode = "failure_code"
	// FieldFailureMessage holds the string denoting the failure_message field in the database.
	FieldFailureMessage = "failure_message"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// EdgeDocument holds the string denoting the document edge name in mutations.
	EdgeDocument = "document"
	// EdgeChunks holds the string denoting the chunks edge name in mutations.
	EdgeChunks = "chunks"
	// Table holds the table name of the ragdocumentversion in the database.
	Table = "rag_document_versions"
	// DocumentTable is the table that holds the document relation/edge.
	DocumentTable = "rag_document_versions"
	// DocumentInverseTable is the table name for the RagDocument entity.
	// It exists in this package in order to avoid circular dependency with the "ragdocument" package.
	DocumentInverseTable = "rag_documents"
	// DocumentColumn is the table column denoting the document relation/edge.
	DocumentColumn = "document_id"
	// ChunksTable is the table that holds the chunks relation/edge.
	ChunksTable = "rag_chunks"
	// ChunksInverseTable is the table name for the RagChunk entity.
	// It exists in this package in order to avoid circular dependency with the "ragchunk" package.
	ChunksInverseTable = "rag_chunks"
	// ChunksColumn is the table column denoting the chunks relation/edge.
	ChunksColumn = "document_version_id"
)

// Columns holds all SQL columns for ragdocumentversion fields.
var Columns = []string{
	FieldID,
	FieldIngestionID,
	FieldDocumentID,
	FieldVersion,
	FieldFileName,
	FieldContentHash,
	FieldOriginalMarkdown,
	FieldSourceBytes,
	FieldStatus,
	FieldStage,
	FieldChunkCount,
	FieldEmbeddedChunkCount,
	FieldFailureCode,
	FieldFailureMessage,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCompletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	FileNameValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// StageValidator is a validator for the "stage" field. It is called by the builders before save.
	StageValidator func(string) error
	// DefaultChunkCount holds the default value on creation for the "chunk_count" field.
	DefaultChunkCount int
	// DefaultEmbeddedChunkCount holds the default value on creation for the "embedded_chunk_count" field.
	DefaultEmbeddedChunkCount int
	// FailureCodeValidator is a validator for the "failure_code" field. It is called by the builders before save.
	FailureCodeValidator func(string) error
	// FailureMessageValidator is a validator for the "failure_message" field. It is called by the builders before save.
	FailureMessageValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the RagDocumentVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIngestionID orders the results by the ingestion_id field.
func ByIngestionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIngestionID, opts...).ToFunc()
}

// ByDocumentID orders the results by the document_id field.
func ByDocumentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByFileName orders the results by the file_name field.
func ByFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileName, opts...).ToFunc()
}

// ByContentHash orders the results by the content_hash field.
func ByContentHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentHash, opts...).ToFunc()
}

// ByOriginalMarkdown orders the results by the original_markdown field.
func ByOriginalMarkdown(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalMarkdown, opts...).ToFunc()
}

// BySourceBytes orders the results by the source_bytes field.
func BySourceBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceBytes, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStage orders the results by the stage field.
func ByStage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStage, opts...).ToFunc()
}

// ByChunkCount orders the results by the chunk_count field.
func ByChunkCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChunkCount, opts...).ToFunc()
}

// ByEmbeddedChunkCount orders the results by the embedded_chunk_count field.
func ByEmbeddedChunkCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmbeddedChunkCount, opts...).ToFunc()
}

// ByFailureCode orders the results by the failure_code field.
func ByFailureCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureCode, opts...).ToFunc()
}

// ByFailureMessage orders the results by the failure_message field.
func ByFailureMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureMessage, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByDocumentField orders the results by document field.
func ByDocumentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDocumentStep(), sql.OrderByField(field, opts...))
	}
}

// ByChunksCount orders the results by chunks count.
func ByChunksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChunksStep(), opts...)
	}
}

// ByChunks orders the results by chunks terms.
func ByChunks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChunksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDocumentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DocumentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DocumentTable, DocumentColumn),
	)
}
func newChunksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChunksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChunksTable, ChunksColumn),
	)
}
