// Code generated by ent, DO NOT EDIT.

package ragdocumentversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/PolarishT/sales-agent/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldID, id))
}

// IngestionID applies equality check predicate on the "ingestion_id" field. It's identical to IngestionIDEQ.
func IngestionID(v uuid.UUID) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldIngestionID, v))
}

// DocumentID applies equality check predicate on the "document_id" field. It's identical to DocumentIDEQ.
func DocumentID(v int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldDocumentID, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldVersion, v))
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldFileName, v))
}

// ContentHash applies equality check predicate on the "content_hash" field. It's identical to ContentHashEQ.
func ContentHash(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldContentHash, v))
}

// OriginalMarkdown applies equality check predicate on the "original_markdown" field. It's identical to OriginalMarkdownEQ.
func OriginalMarkdown(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldOriginalMarkdown, v))
}

// SourceBytes applies equality check predicate on the "source_bytes" field. It's identical to SourceBytesEQ.
func SourceBytes(v int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldSourceBytes, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldStatus, v))
}

// Stage applies equality check predicate on the "stage" field. It's identical to StageEQ.
func Stage(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldStage, v))
}

// ChunkCount applies equality check predicate on the "chunk_count" field. It's identical to ChunkCountEQ.
func ChunkCount(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldChunkCount, v))
}

// EmbeddedChunkCount applies equality check predicate on the "embedded_chunk_count" field. It's identical to EmbeddedChunkCountEQ.
func EmbeddedChunkCount(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldEmbeddedChunkCount, v))
}

// FailureCode applies equality check predicate on the "failure_code" field. It's identical to FailureCodeEQ.
func FailureCode(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldFailureCode, v))
}

// FailureMessage applies equality check predicate on the "failure_message" field. It's identical to FailureMessageEQ.
func FailureMessage(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldFailureMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldCompletedAt, v))
}

// IngestionIDEQ applies the EQ predicate on the "ingestion_id" field.
func IngestionIDEQ(v uuid.UUID) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldIngestionID, v))
}

// IngestionIDNEQ applies the NEQ predicate on the "ingestion_id" field.
func IngestionIDNEQ(v uuid.UUID) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldIngestionID, v))
}

// IngestionIDIn applies the In predicate on the "ingestion_id" field.
func IngestionIDIn(vs ...uuid.UUID) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldIngestionID, vs...))
}

// IngestionIDNotIn applies the NotIn predicate on the "ingestion_id" field.
func IngestionIDNotIn(vs ...uuid.UUID) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldIngestionID, vs...))
}

// IngestionIDGT applies the GT predicate on the "ingestion_id" field.
func IngestionIDGT(v uuid.UUID) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldIngestionID, v))
}

// IngestionIDGTE applies the GTE predicate on the "ingestion_id" field.
func IngestionIDGTE(v uuid.UUID) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldIngestionID, v))
}

// IngestionIDLT applies the LT predicate on the "ingestion_id" field.
func IngestionIDLT(v uuid.UUID) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldIngestionID, v))
}

// IngestionIDLTE applies the LTE predicate on the "ingestion_id" field.
func IngestionIDLTE(v uuid.UUID) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldIngestionID, v))
}

// DocumentIDEQ applies the EQ predicate on the "document_id" field.
func DocumentIDEQ(v int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldDocumentID, v))
}

// DocumentIDNEQ applies the NEQ predicate on the "document_id" field.
func DocumentIDNEQ(v int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldDocumentID, v))
}

// DocumentIDIn applies the In predicate on the "document_id" field.
func DocumentIDIn(vs ...int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldDocumentID, vs...))
}

// DocumentIDNotIn applies the NotIn predicate on the "document_id" field.
func DocumentIDNotIn(vs ...int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldDocumentID, vs...))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldVersion, v))
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldFileName, v))
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldContains(FieldFileName, v))
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldHasPrefix(FieldFileName, v))
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldHasSuffix(FieldFileName, v))
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEqualFold(FieldFileName, v))
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldContainsFold(FieldFileName, v))
}

// ContentHashEQ applies the EQ predicate on the "content_hash" field.
func ContentHashEQ(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldContentHash, v))
}

// ContentHashNEQ applies the NEQ predicate on the "content_hash" field.
func ContentHashNEQ(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldContentHash, v))
}

// ContentHashIn applies the In predicate on the "content_hash" field.
func ContentHashIn(vs ...string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldContentHash, vs...))
}

// ContentHashNotIn applies the NotIn predicate on the "content_hash" field.
func ContentHashNotIn(vs ...string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldContentHash, vs...))
}

// ContentHashGT applies the GT predicate on the "content_hash" field.
func ContentHashGT(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldContentHash, v))
}

// ContentHashGTE applies the GTE predicate on the "content_hash" field.
func ContentHashGTE(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldContentHash, v))
}

// ContentHashLT applies the LT predicate on the "content_hash" field.
func ContentHashLT(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldContentHash, v))
}

// ContentHashLTE applies the LTE predicate on the "content_hash" field.
func ContentHashLTE(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldContentHash, v))
}

// ContentHashContains applies the Contains predicate on the "content_hash" field.
func ContentHashContains(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldContains(FieldContentHash, v))
}

// ContentHashHasPrefix applies the HasPrefix predicate on the "content_hash" field.
func ContentHashHasPrefix(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldHasPrefix(FieldContentHash, v))
}

// ContentHashHasSuffix applies the HasSuffix predicate on the "content_hash" field.
func ContentHashHasSuffix(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldHasSuffix(FieldContentHash, v))
}

// ContentHashEqualFold applies the EqualFold predicate on the "content_hash" field.
func ContentHashEqualFold(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEqualFold(FieldContentHash, v))
}

// ContentHashContainsFold applies the ContainsFold predicate on the "content_hash" field.
func ContentHashContainsFold(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldContainsFold(FieldContentHash, v))
}

// OriginalMarkdownEQ applies the EQ predicate on the "original_markdown" field.
func OriginalMarkdownEQ(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldOriginalMarkdown, v))
}

// OriginalMarkdownNEQ applies the NEQ predicate on the "original_markdown" field.
func OriginalMarkdownNEQ(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldOriginalMarkdown, v))
}

// OriginalMarkdownIn applies the In predicate on the "original_markdown" field.
func OriginalMarkdownIn(vs ...string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldOriginalMarkdown, vs...))
}

// OriginalMarkdownNotIn applies the NotIn predicate on the "original_markdown" field.
func OriginalMarkdownNotIn(vs ...string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldOriginalMarkdown, vs...))
}

// OriginalMarkdownGT applies the GT predicate on the "original_markdown" field.
func OriginalMarkdownGT(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldOriginalMarkdown, v))
}

// OriginalMarkdownGTE applies the GTE predicate on the "original_markdown" field.
func OriginalMarkdownGTE(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldOriginalMarkdown, v))
}

// OriginalMarkdownLT applies the LT predicate on the "original_markdown" field.
func OriginalMarkdownLT(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldOriginalMarkdown, v))
}

// OriginalMarkdownLTE applies the LTE predicate on the "original_markdown" field.
func OriginalMarkdownLTE(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldOriginalMarkdown, v))
}

// OriginalMarkdownContains applies the Contains predicate on the "original_markdown" field.
func OriginalMarkdownContains(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldContains(FieldOriginalMarkdown, v))
}

// OriginalMarkdownHasPrefix applies the HasPrefix predicate on the "original_markdown" field.
func OriginalMarkdownHasPrefix(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldHasPrefix(FieldOriginalMarkdown, v))
}

// OriginalMarkdownHasSuffix applies the HasSuffix predicate on the "original_markdown" field.
func OriginalMarkdownHasSuffix(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldHasSuffix(FieldOriginalMarkdown, v))
}

// OriginalMarkdownEqualFold applies the EqualFold predicate on the "original_markdown" field.
func OriginalMarkdownEqualFold(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEqualFold(FieldOriginalMarkdown, v))
}

// OriginalMarkdownContainsFold applies the ContainsFold predicate on the "original_markdown" field.
func OriginalMarkdownContainsFold(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldContainsFold(FieldOriginalMarkdown, v))
}

// SourceBytesEQ applies the EQ predicate on the "source_bytes" field.
func SourceBytesEQ(v int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldSourceBytes, v))
}

// SourceBytesNEQ applies the NEQ predicate on the "source_bytes" field.
func SourceBytesNEQ(v int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldSourceBytes, v))
}

// SourceBytesIn applies the In predicate on the "source_bytes" field.
func SourceBytesIn(vs ...int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldSourceBytes, vs...))
}

// SourceBytesNotIn applies the NotIn predicate on the "source_bytes" field.
func SourceBytesNotIn(vs ...int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldSourceBytes, vs...))
}

// SourceBytesGT applies the GT predicate on the "source_bytes" field.
func SourceBytesGT(v int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldSourceBytes, v))
}

// SourceBytesGTE applies the GTE predicate on the "source_bytes" field.
func SourceBytesGTE(v int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldSourceBytes, v))
}

// SourceBytesLT applies the LT predicate on the "source_bytes" field.
func SourceBytesLT(v int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldSourceBytes, v))
}

// SourceBytesLTE applies the LTE predicate on the "source_bytes" field.
func SourceBytesLTE(v int64) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldSourceBytes, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldContainsFold(FieldStatus, v))
}

// StageEQ applies the EQ predicate on the "stage" field.
func StageEQ(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldStage, v))
}

// StageNEQ applies the NEQ predicate on the "stage" field.
func StageNEQ(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldStage, v))
}

// StageIn applies the In predicate on the "stage" field.
func StageIn(vs ...string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldStage, vs...))
}

// StageNotIn applies the NotIn predicate on the "stage" field.
func StageNotIn(vs ...string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldStage, vs...))
}

// StageGT applies the GT predicate on the "stage" field.
func StageGT(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldStage, v))
}

// StageGTE applies the GTE predicate on the "stage" field.
func StageGTE(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldStage, v))
}

// StageLT applies the LT predicate on the "stage" field.
func StageLT(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldStage, v))
}

// StageLTE applies the LTE predicate on the "stage" field.
func StageLTE(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldStage, v))
}

// StageContains applies the Contains predicate on the "stage" field.
func StageContains(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldContains(FieldStage, v))
}

// StageHasPrefix applies the HasPrefix predicate on the "stage" field.
func StageHasPrefix(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldHasPrefix(FieldStage, v))
}

// StageHasSuffix applies the HasSuffix predicate on the "stage" field.
func StageHasSuffix(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldHasSuffix(FieldStage, v))
}

// StageEqualFold applies the EqualFold predicate on the "stage" field.
func StageEqualFold(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEqualFold(FieldStage, v))
}

// StageContainsFold applies the ContainsFold predicate on the "stage" field.
func StageContainsFold(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldContainsFold(FieldStage, v))
}

// ChunkCountEQ applies the EQ predicate on the "chunk_count" field.
func ChunkCountEQ(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldChunkCount, v))
}

// ChunkCountNEQ applies the NEQ predicate on the "chunk_count" field.
func ChunkCountNEQ(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldChunkCount, v))
}

// ChunkCountIn applies the In predicate on the "chunk_count" field.
func ChunkCountIn(vs ...int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldChunkCount, vs...))
}

// ChunkCountNotIn applies the NotIn predicate on the "chunk_count" field.
func ChunkCountNotIn(vs ...int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldChunkCount, vs...))
}

// ChunkCountGT applies the GT predicate on the "chunk_count" field.
func ChunkCountGT(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldChunkCount, v))
}

// ChunkCountGTE applies the GTE predicate on the "chunk_count" field.
func ChunkCountGTE(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldChunkCount, v))
}

// ChunkCountLT applies the LT predicate on the "chunk_count" field.
func ChunkCountLT(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldChunkCount, v))
}

// ChunkCountLTE applies the LTE predicate on the "chunk_count" field.
func ChunkCountLTE(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldChunkCount, v))
}

// EmbeddedChunkCountEQ applies the EQ predicate on the "embedded_chunk_count" field.
func EmbeddedChunkCountEQ(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldEmbeddedChunkCount, v))
}

// EmbeddedChunkCountNEQ applies the NEQ predicate on the "embedded_chunk_count" field.
func EmbeddedChunkCountNEQ(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldEmbeddedChunkCount, v))
}

// EmbeddedChunkCountIn applies the In predicate on the "embedded_chunk_count" field.
func EmbeddedChunkCountIn(vs ...int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldEmbeddedChunkCount, vs...))
}

// EmbeddedChunkCountNotIn applies the NotIn predicate on the "embedded_chunk_count" field.
func EmbeddedChunkCountNotIn(vs ...int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldEmbeddedChunkCount, vs...))
}

// EmbeddedChunkCountGT applies the GT predicate on the "embedded_chunk_count" field.
func EmbeddedChunkCountGT(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldEmbeddedChunkCount, v))
}

// EmbeddedChunkCountGTE applies the GTE predicate on the "embedded_chunk_count" field.
func EmbeddedChunkCountGTE(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldEmbeddedChunkCount, v))
}

// EmbeddedChunkCountLT applies the LT predicate on the "embedded_chunk_count" field.
func EmbeddedChunkCountLT(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldEmbeddedChunkCount, v))
}

// EmbeddedChunkCountLTE applies the LTE predicate on the "embedded_chunk_count" field.
func EmbeddedChunkCountLTE(v int) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldEmbeddedChunkCount, v))
}

// FailureCodeEQ applies the EQ predicate on the "failure_code" field.
func FailureCodeEQ(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldFailureCode, v))
}

// FailureCodeNEQ applies the NEQ predicate on the "failure_code" field.
func FailureCodeNEQ(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldFailureCode, v))
}

// FailureCodeIn applies the In predicate on the "failure_code" field.
func FailureCodeIn(vs ...string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldFailureCode, vs...))
}

// FailureCodeNotIn applies the NotIn predicate on the "failure_code" field.
func FailureCodeNotIn(vs ...string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldFailureCode, vs...))
}

// FailureCodeGT applies the GT predicate on the "failure_code" field.
func FailureCodeGT(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldFailureCode, v))
}

// FailureCodeGTE applies the GTE predicate on the "failure_code" field.
func FailureCodeGTE(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldFailureCode, v))
}

// FailureCodeLT applies the LT predicate on the "failure_code" field.
func FailureCodeLT(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldFailureCode, v))
}

// FailureCodeLTE applies the LTE predicate on the "failure_code" field.
func FailureCodeLTE(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldFailureCode, v))
}

// FailureCodeContains applies the Contains predicate on the "failure_code" field.
func FailureCodeContains(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldContains(FieldFailureCode, v))
}

// FailureCodeHasPrefix applies the HasPrefix predicate on the "failure_code" field.
func FailureCodeHasPrefix(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldHasPrefix(FieldFailureCode, v))
}

// FailureCodeHasSuffix applies the HasSuffix predicate on the "failure_code" field.
func FailureCodeHasSuffix(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldHasSuffix(FieldFailureCode, v))
}

// FailureCodeIsNil applies the IsNil predicate on the "failure_code" field.
func FailureCodeIsNil() predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIsNull(FieldFailureCode))
}

// FailureCodeNotNil applies the NotNil predicate on the "failure_code" field.
func FailureCodeNotNil() predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotNull(FieldFailureCode))
}

// FailureCodeEqualFold applies the EqualFold predicate on the "failure_code" field.
func FailureCodeEqualFold(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEqualFold(FieldFailureCode, v))
}

// FailureCodeContainsFold applies the ContainsFold predicate on the "failure_code" field.
func FailureCodeContainsFold(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldContainsFold(FieldFailureCode, v))
}

// FailureMessageEQ applies the EQ predicate on the "failure_message" field.
func FailureMessageEQ(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldFailureMessage, v))
}

// FailureMessageNEQ applies the NEQ predicate on the "failure_message" field.
func FailureMessageNEQ(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldFailureMessage, v))
}

// FailureMessageIn applies the In predicate on the "failure_message" field.
func FailureMessageIn(vs ...string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldFailureMessage, vs...))
}

// FailureMessageNotIn applies the NotIn predicate on the "failure_message" field.
func FailureMessageNotIn(vs ...string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldFailureMessage, vs...))
}

// FailureMessageGT applies the GT predicate on the "failure_message" field.
func FailureMessageGT(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldFailureMessage, v))
}

// FailureMessageGTE applies the GTE predicate on the "failure_message" field.
func FailureMessageGTE(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldFailureMessage, v))
}

// FailureMessageLT applies the LT predicate on the "failure_message" field.
func FailureMessageLT(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldFailureMessage, v))
}

// FailureMessageLTE applies the LTE predicate on the "failure_message" field.
func FailureMessageLTE(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldFailureMessage, v))
}

// FailureMessageContains applies the Contains predicate on the "failure_message" field.
func FailureMessageContains(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldContains(FieldFailureMessage, v))
}

// FailureMessageHasPrefix applies the HasPrefix predicate on the "failure_message" field.
func FailureMessageHasPrefix(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldHasPrefix(FieldFailureMessage, v))
}

// FailureMessageHasSuffix applies the HasSuffix predicate on the "failure_message" field.
func FailureMessageHasSuffix(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldHasSuffix(FieldFailureMessage, v))
}

// FailureMessageIsNil applies the IsNil predicate on the "failure_message" field.
func FailureMessageIsNil() predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIsNull(FieldFailureMessage))
}

// FailureMessageNotNil applies the NotNil predicate on the "failure_message" field.
func FailureMessageNotNil() predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotNull(FieldFailureMessage))
}

// FailureMessageEqualFold applies the EqualFold predicate on the "failure_message" field.
func FailureMessageEqualFold(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEqualFold(FieldFailureMessage, v))
}

// FailureMessageContainsFold applies the ContainsFold predicate on the "failure_message" field.
func FailureMessageContainsFold(v string) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldContainsFold(FieldFailureMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldUpdatedAt, v))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.FieldNotNull(FieldCompletedAt))
}

// HasDocument applies the HasEdge predicate on the "document" edge.
func HasDocument() predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DocumentTable, DocumentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDocumentWith applies the HasEdge predicate on the "document" edge with a given conditions (other predicates).
func HasDocumentWith(preds ...predicate.RagDocument) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(func(s *sql.Selector) {
		step := newDocumentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChunks applies the HasEdge predicate on the "chunks" edge.
func HasChunks() predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChunksTable, ChunksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChunksWith applies the HasEdge predicate on the "chunks" edge with a given conditions (other predicates).
func HasChunksWith(preds ...predicate.RagChunk) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(func(s *sql.Selector) {
		step := newChunksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RagDocumentVersion) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RagDocumentVersion) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RagDocumentVersion) predicate.RagDocumentVersion {
	return predicate.RagDocumentVersion(sql.NotPredicates(p))
}
