// Code generated by hertz generator.

package rag_ingestion

import (
	"context"

	rag_ingestion "github.com/PolarishT/sales-agent/biz/model/rag_ingestion"
	httpapi "github.com/PolarishT/sales-agent/internal/http"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Keep the generated request model import while this temporary protocol adapter
// does not yet bind requests to an application service.
var _ = rag_ingestion.CreateIngestionRequest{}

// CreateIngestion .
// @router /api/v1/rag/ingestions [POST]
func CreateIngestion(ctx context.Context, requestContext *app.RequestContext) {
	httpapi.WriteError(requestContext, consts.StatusServiceUnavailable, "unavailable", "INGESTION_UNAVAILABLE", "文档导入服务暂不可用")
}

// GetIngestion .
// @router /api/v1/rag/ingestions/:ingestion_id [GET]
func GetIngestion(ctx context.Context, requestContext *app.RequestContext) {
	httpapi.WriteError(requestContext, consts.StatusServiceUnavailable, "unavailable", "INGESTION_UNAVAILABLE", "文档导入服务暂不可用")
}
