// Code generated by ent, DO NOT EDIT.

package ragchunk

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/PolarishT/sales-agent/ent/predicate"
	pgvector "github.com/pgvector/pgvector-go"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLTE(FieldID, id))
}

// DocumentVersionID applies equality check predicate on the "document_version_id" field. It's identical to DocumentVersionIDEQ.
func DocumentVersionID(v int64) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldDocumentVersionID, v))
}

// ChunkIndex applies equality check predicate on the "chunk_index" field. It's identical to ChunkIndexEQ.
func ChunkIndex(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldChunkIndex, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldContent, v))
}

// EmbeddingContent applies equality check predicate on the "embedding_content" field. It's identical to EmbeddingContentEQ.
func EmbeddingContent(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldEmbeddingContent, v))
}

// StartLine applies equality check predicate on the "start_line" field. It's identical to StartLineEQ.
func StartLine(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldStartLine, v))
}

// EndLine applies equality check predicate on the "end_line" field. It's identical to EndLineEQ.
func EndLine(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldEndLine, v))
}

// EstimatedTokens applies equality check predicate on the "estimated_tokens" field. It's identical to EstimatedTokensEQ.
func EstimatedTokens(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldEstimatedTokens, v))
}

// ContentHash applies equality check predicate on the "content_hash" field. It's identical to ContentHashEQ.
func ContentHash(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldContentHash, v))
}

// Embedding applies equality check predicate on the "embedding" field. It's identical to EmbeddingEQ.
func Embedding(v pgvector.Vector) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldEmbedding, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldCreatedAt, v))
}

// DocumentVersionIDEQ applies the EQ predicate on the "document_version_id" field.
func DocumentVersionIDEQ(v int64) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldDocumentVersionID, v))
}

// DocumentVersionIDNEQ applies the NEQ predicate on the "document_version_id" field.
func DocumentVersionIDNEQ(v int64) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNEQ(FieldDocumentVersionID, v))
}

// DocumentVersionIDIn applies the In predicate on the "document_version_id" field.
func DocumentVersionIDIn(vs ...int64) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldIn(FieldDocumentVersionID, vs...))
}

// DocumentVersionIDNotIn applies the NotIn predicate on the "document_version_id" field.
func DocumentVersionIDNotIn(vs ...int64) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNotIn(FieldDocumentVersionID, vs...))
}

// ChunkIndexEQ applies the EQ predicate on the "chunk_index" field.
func ChunkIndexEQ(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldChunkIndex, v))
}

// ChunkIndexNEQ applies the NEQ predicate on the "chunk_index" field.
func ChunkIndexNEQ(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNEQ(FieldChunkIndex, v))
}

// ChunkIndexIn applies the In predicate on the "chunk_index" field.
func ChunkIndexIn(vs ...int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldIn(FieldChunkIndex, vs...))
}

// ChunkIndexNotIn applies the NotIn predicate on the "chunk_index" field.
func ChunkIndexNotIn(vs ...int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNotIn(FieldChunkIndex, vs...))
}

// ChunkIndexGT applies the GT predicate on the "chunk_index" field.
func ChunkIndexGT(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGT(FieldChunkIndex, v))
}

// ChunkIndexGTE applies the GTE predicate on the "chunk_index" field.
func ChunkIndexGTE(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGTE(FieldChunkIndex, v))
}

// ChunkIndexLT applies the LT predicate on the "chunk_index" field.
func ChunkIndexLT(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLT(FieldChunkIndex, v))
}

// ChunkIndexLTE applies the LTE predicate on the "chunk_index" field.
func ChunkIndexLTE(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLTE(FieldChunkIndex, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldContainsFold(FieldContent, v))
}

// EmbeddingContentEQ applies the EQ predicate on the "embedding_content" field.
func EmbeddingContentEQ(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldEmbeddingContent, v))
}

// EmbeddingContentNEQ applies the NEQ predicate on the "embedding_content" field.
func EmbeddingContentNEQ(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNEQ(FieldEmbeddingContent, v))
}

// EmbeddingContentIn applies the In predicate on the "embedding_content" field.
func EmbeddingContentIn(vs ...string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldIn(FieldEmbeddingContent, vs...))
}

// EmbeddingContentNotIn applies the NotIn predicate on the "embedding_content" field.
func EmbeddingContentNotIn(vs ...string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNotIn(FieldEmbeddingContent, vs...))
}

// EmbeddingContentGT applies the GT predicate on the "embedding_content" field.
func EmbeddingContentGT(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGT(FieldEmbeddingContent, v))
}

// EmbeddingContentGTE applies the GTE predicate on the "embedding_content" field.
func EmbeddingContentGTE(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGTE(FieldEmbeddingContent, v))
}

// EmbeddingContentLT applies the LT predicate on the "embedding_content" field.
func EmbeddingContentLT(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLT(FieldEmbeddingContent, v))
}

// EmbeddingContentLTE applies the LTE predicate on the "embedding_content" field.
func EmbeddingContentLTE(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLTE(FieldEmbeddingContent, v))
}

// EmbeddingContentContains applies the Contains predicate on the "embedding_content" field.
func EmbeddingContentContains(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldContains(FieldEmbeddingContent, v))
}

// EmbeddingContentHasPrefix applies the HasPrefix predicate on the "embedding_content" field.
func EmbeddingContentHasPrefix(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldHasPrefix(FieldEmbeddingContent, v))
}

// EmbeddingContentHasSuffix applies the HasSuffix predicate on the "embedding_content" field.
func EmbeddingContentHasSuffix(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldHasSuffix(FieldEmbeddingContent, v))
}

// EmbeddingContentEqualFold applies the EqualFold predicate on the "embedding_content" field.
func EmbeddingContentEqualFold(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEqualFold(FieldEmbeddingContent, v))
}

// EmbeddingContentContainsFold applies the ContainsFold predicate on the "embedding_content" field.
func EmbeddingContentContainsFold(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldContainsFold(FieldEmbeddingContent, v))
}

// StartLineEQ applies the EQ predicate on the "start_line" field.
func StartLineEQ(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldStartLine, v))
}

// StartLineNEQ applies the NEQ predicate on the "start_line" field.
func StartLineNEQ(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNEQ(FieldStartLine, v))
}

// StartLineIn applies the In predicate on the "start_line" field.
func StartLineIn(vs ...int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldIn(FieldStartLine, vs...))
}

// StartLineNotIn applies the NotIn predicate on the "start_line" field.
func StartLineNotIn(vs ...int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNotIn(FieldStartLine, vs...))
}

// StartLineGT applies the GT predicate on the "start_line" field.
func StartLineGT(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGT(FieldStartLine, v))
}

// StartLineGTE applies the GTE predicate on the "start_line" field.
func StartLineGTE(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGTE(FieldStartLine, v))
}

// StartLineLT applies the LT predicate on the "start_line" field.
func StartLineLT(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLT(FieldStartLine, v))
}

// StartLineLTE applies the LTE predicate on the "start_line" field.
func StartLineLTE(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLTE(FieldStartLine, v))
}

// EndLineEQ applies the EQ predicate on the "end_line" field.
func EndLineEQ(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldEndLine, v))
}

// EndLineNEQ applies the NEQ predicate on the "end_line" field.
func EndLineNEQ(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNEQ(FieldEndLine, v))
}

// EndLineIn applies the In predicate on the "end_line" field.
func EndLineIn(vs ...int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldIn(FieldEndLine, vs...))
}

// EndLineNotIn applies the NotIn predicate on the "end_line" field.
func EndLineNotIn(vs ...int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNotIn(FieldEndLine, vs...))
}

// EndLineGT applies the GT predicate on the "end_line" field.
func EndLineGT(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGT(FieldEndLine, v))
}

// EndLineGTE applies the GTE predicate on the "end_line" field.
func EndLineGTE(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGTE(FieldEndLine, v))
}

// EndLineLT applies the LT predicate on the "end_line" field.
func EndLineLT(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLT(FieldEndLine, v))
}

// EndLineLTE applies the LTE predicate on the "end_line" field.
func EndLineLTE(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLTE(FieldEndLine, v))
}

// EstimatedTokensEQ applies the EQ predicate on the "estimated_tokens" field.
func EstimatedTokensEQ(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldEstimatedTokens, v))
}

// EstimatedTokensNEQ applies the NEQ predicate on the "estimated_tokens" field.
func EstimatedTokensNEQ(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNEQ(FieldEstimatedTokens, v))
}

// EstimatedTokensIn applies the In predicate on the "estimated_tokens" field.
func EstimatedTokensIn(vs ...int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldIn(FieldEstimatedTokens, vs...))
}

// EstimatedTokensNotIn applies the NotIn predicate on the "estimated_tokens" field.
func EstimatedTokensNotIn(vs ...int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNotIn(FieldEstimatedTokens, vs...))
}

// EstimatedTokensGT applies the GT predicate on the "estimated_tokens" field.
func EstimatedTokensGT(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGT(FieldEstimatedTokens, v))
}

// EstimatedTokensGTE applies the GTE predicate on the "estimated_tokens" field.
func EstimatedTokensGTE(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGTE(FieldEstimatedTokens, v))
}

// EstimatedTokensLT applies the LT predicate on the "estimated_tokens" field.
func EstimatedTokensLT(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLT(FieldEstimatedTokens, v))
}

// EstimatedTokensLTE applies the LTE predicate on the "estimated_tokens" field.
func EstimatedTokensLTE(v int) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLTE(FieldEstimatedTokens, v))
}

// ContentHashEQ applies the EQ predicate on the "content_hash" field.
func ContentHashEQ(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldContentHash, v))
}

// ContentHashNEQ applies the NEQ predicate on the "content_hash" field.
func ContentHashNEQ(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNEQ(FieldContentHash, v))
}

// ContentHashIn applies the In predicate on the "content_hash" field.
func ContentHashIn(vs ...string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldIn(FieldContentHash, vs...))
}

// ContentHashNotIn applies the NotIn predicate on the "content_hash" field.
func ContentHashNotIn(vs ...string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNotIn(FieldContentHash, vs...))
}

// ContentHashGT applies the GT predicate on the "content_hash" field.
func ContentHashGT(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGT(FieldContentHash, v))
}

// ContentHashGTE applies the GTE predicate on the "content_hash" field.
func ContentHashGTE(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGTE(FieldContentHash, v))
}

// ContentHashLT applies the LT predicate on the "content_hash" field.
func ContentHashLT(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLT(FieldContentHash, v))
}

// ContentHashLTE applies the LTE predicate on the "content_hash" field.
func ContentHashLTE(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLTE(FieldContentHash, v))
}

// ContentHashContains applies the Contains predicate on the "content_hash" field.
func ContentHashContains(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldContains(FieldContentHash, v))
}

// ContentHashHasPrefix applies the HasPrefix predicate on the "content_hash" field.
func ContentHashHasPrefix(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldHasPrefix(FieldContentHash, v))
}

// ContentHashHasSuffix applies the HasSuffix predicate on the "content_hash" field.
func ContentHashHasSuffix(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldHasSuffix(FieldContentHash, v))
}

// ContentHashEqualFold applies the EqualFold predicate on the "content_hash" field.
func ContentHashEqualFold(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEqualFold(FieldContentHash, v))
}

// ContentHashContainsFold applies the ContainsFold predicate on the "content_hash" field.
func ContentHashContainsFold(v string) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldContainsFold(FieldContentHash, v))
}

// EmbeddingEQ applies the EQ predicate on the "embedding" field.
func EmbeddingEQ(v pgvector.Vector) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldEmbedding, v))
}

// EmbeddingNEQ applies the NEQ predicate on the "embedding" field.
func EmbeddingNEQ(v pgvector.Vector) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNEQ(FieldEmbedding, v))
}

// EmbeddingIn applies the In predicate on the "embedding" field.
func EmbeddingIn(vs ...pgvector.Vector) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldIn(FieldEmbedding, vs...))
}

// EmbeddingNotIn applies the NotIn predicate on the "embedding" field.
func EmbeddingNotIn(vs ...pgvector.Vector) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNotIn(FieldEmbedding, vs...))
}

// EmbeddingGT applies the GT predicate on the "embedding" field.
func EmbeddingGT(v pgvector.Vector) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGT(FieldEmbedding, v))
}

// EmbeddingGTE applies the GTE predicate on the "embedding" field.
func EmbeddingGTE(v pgvector.Vector) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGTE(FieldEmbedding, v))
}

// EmbeddingLT applies the LT predicate on the "embedding" field.
func EmbeddingLT(v pgvector.Vector) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLT(FieldEmbedding, v))
}

// EmbeddingLTE applies the LTE predicate on the "embedding" field.
func EmbeddingLTE(v pgvector.Vector) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLTE(FieldEmbedding, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RagChunk {
	return predicate.RagChunk(sql.FieldLTE(FieldCreatedAt, v))
}

// HasDocumentVersion applies the HasEdge predicate on the "document_version" edge.
func HasDocumentVersion() predicate.RagChunk {
	return predicate.RagChunk(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DocumentVersionTable, DocumentVersionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDocumentVersionWith applies the HasEdge predicate on the "document_version" edge with a given conditions (other predicates).
func HasDocumentVersionWith(preds ...predicate.RagDocumentVersion) predicate.RagChunk {
	return predicate.RagChunk(func(s *sql.Selector) {
		step := newDocumentVersionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RagChunk) predicate.RagChunk {
	return predicate.RagChunk(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RagChunk) predicate.RagChunk {
	return predicate.RagChunk(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RagChunk) predicate.RagChunk {
	return predicate.RagChunk(sql.NotPredicates(p))
}
