// Code generated by hertz generator.

package rag_ingestion

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ragMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createingestionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ingestionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getingestionMw() []app.HandlerFunc {
	// your code...
	return nil
}
