// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PolarishT/sales-agent/ent/ragchunk"
	"github.com/PolarishT/sales-agent/ent/ragdocumentversion"
	pgvector "github.com/pgvector/pgvector-go"
)

// RagChunk is the model entity for the RagChunk schema.
type RagChunk struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// DocumentVersionID holds the value of the "document_version_id" field.
	DocumentVersionID int64 `json:"document_version_id,omitempty"`
	// ChunkIndex holds the value of the "chunk_index" field.
	ChunkIndex int `json:"chunk_index,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// EmbeddingContent holds the value of the "embedding_content" field.
	EmbeddingContent string `json:"embedding_content,omitempty"`
	// HeadingPath holds the value of the "heading_path" field.
	HeadingPath []string `json:"heading_path,omitempty"`
	// StartLine holds the value of the "start_line" field.
	StartLine int `json:"start_line,omitempty"`
	// EndLine holds the value of the "end_line" field.
	EndLine int `json:"end_line,omitempty"`
	// EstimatedTokens holds the value of the "estimated_tokens" field.
	EstimatedTokens int `json:"estimated_tokens,omitempty"`
	// ContentHash holds the value of the "content_hash" field.
	ContentHash string `json:"content_hash,omitempty"`
	// Embedding holds the value of the "embedding" field.
	Embedding pgvector.Vector `json:"embedding,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RagChunkQuery when eager-loading is set.
	Edges        RagChunkEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RagChunkEdges holds the relations/edges for other nodes in the graph.
type RagChunkEdges struct {
	// DocumentVersion holds the value of the document_version edge.
	DocumentVersion *RagDocumentVersion `json:"document_version,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// DocumentVersionOrErr returns the DocumentVersion value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RagChunkEdges) DocumentVersionOrErr() (*RagDocumentVersion, error) {
	if e.DocumentVersion != nil {
		return e.DocumentVersion, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: ragdocumentversion.Label}
	}
	return nil, &NotLoadedError{edge: "document_version"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RagChunk) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ragchunk.FieldHeadingPath:
			values[i] = new([]byte)
		case ragchunk.FieldEmbedding:
			values[i] = new(pgvector.Vector)
		case ragchunk.FieldID, ragchunk.FieldDocumentVersionID, ragchunk.FieldChunkIndex, ragchunk.FieldStartLine, ragchunk.FieldEndLine, ragchunk.FieldEstimatedTokens:
			values[i] = new(sql.NullInt64)
		case ragchunk.FieldContent, ragchunk.FieldEmbeddingContent, ragchunk.FieldContentHash:
			values[i] = new(sql.NullString)
		case ragchunk.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RagChunk fields.
func (_m *RagChunk) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ragchunk.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ragchunk.FieldDocumentVersionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field document_version_id", values[i])
			} else if value.Valid {
				_m.DocumentVersionID = value.Int64
			}
		case ragchunk.FieldChunkIndex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chunk_index", values[i])
			} else if value.Valid {
				_m.ChunkIndex = int(value.Int64)
			}
		case ragchunk.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case ragchunk.FieldEmbeddingContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field embedding_content", values[i])
			} else if value.Valid {
				_m.EmbeddingContent = value.String
			}
		case ragchunk.FieldHeadingPath:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field heading_path", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.HeadingPath); err != nil {
					return fmt.Errorf("unmarshal field heading_path: %w", err)
				}
			}
		case ragchunk.FieldStartLine:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field start_line", values[i])
			} else if value.Valid {
				_m.StartLine = int(value.Int64)
			}
		case ragchunk.FieldEndLine:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field end_line", values[i])
			} else if value.Valid {
				_m.EndLine = int(value.Int64)
			}
		case ragchunk.FieldEstimatedTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_tokens", values[i])
			} else if value.Valid {
				_m.EstimatedTokens = int(value.Int64)
			}
		case ragchunk.FieldContentHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_hash", values[i])
			} else if value.Valid {
				_m.ContentHash = value.String
			}
		case ragchunk.FieldEmbedding:
			if value, ok := values[i].(*pgvector.Vector); !ok {
				return fmt.Errorf("unexpected type %T for field embedding", values[i])
			} else if value != nil {
				_m.Embedding = *value
			}
		case ragchunk.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RagChunk.
// This includes values selected through modifiers, order, etc.
func (_m *RagChunk) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDocumentVersion queries the "document_version" edge of the RagChunk entity.
func (_m *RagChunk) QueryDocumentVersion() *RagDocumentVersionQuery {
	return NewRagChunkClient(_m.config).QueryDocumentVersion(_m)
}

// Update returns a builder for updating this RagChunk.
// Note that you need to call RagChunk.Unwrap() before calling this method if this RagChunk
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RagChunk) Update() *RagChunkUpdateOne {
	return NewRagChunkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RagChunk entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RagChunk) Unwrap() *RagChunk {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RagChunk is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RagChunk) String() string {
	var builder strings.Builder
	builder.WriteString("RagChunk(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("document_version_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DocumentVersionID))
	builder.WriteString(", ")
	builder.WriteString("chunk_index=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChunkIndex))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("embedding_content=")
	builder.WriteString(_m.EmbeddingContent)
	builder.WriteString(", ")
	builder.WriteString("heading_path=")
	builder.WriteString(fmt.Sprintf("%v", _m.HeadingPath))
	builder.WriteString(", ")
	builder.WriteString("start_line=")
	builder.WriteString(fmt.Sprintf("%v", _m.StartLine))
	builder.WriteString(", ")
	builder.WriteString("end_line=")
	builder.WriteString(fmt.Sprintf("%v", _m.EndLine))
	builder.WriteString(", ")
	builder.WriteString("estimated_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.EstimatedTokens))
	builder.WriteString(", ")
	builder.WriteString("content_hash=")
	builder.WriteString(_m.ContentHash)
	builder.WriteString(", ")
	builder.WriteString("embedding=")
	builder.WriteString(fmt.Sprintf("%v", _m.Embedding))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RagChunks is a parsable slice of RagChunk.
type RagChunks []*RagChunk
