// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PolarishT/sales-agent/ent/ragchunk"
	"github.com/PolarishT/sales-agent/ent/ragdocumentversion"
	pgvector "github.com/pgvector/pgvector-go"
)

// RagChunkCreate is the builder for creating a RagChunk entity.
type RagChunkCreate struct {
	config
	mutation *RagChunkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDocumentVersionID sets the "document_version_id" field.
func (_c *RagChunkCreate) SetDocumentVersionID(v int64) *RagChunkCreate {
	_c.mutation.SetDocumentVersionID(v)
	return _c
}

// SetChunkIndex sets the "chunk_index" field.
func (_c *RagChunkCreate) SetChunkIndex(v int) *RagChunkCreate {
	_c.mutation.SetChunkIndex(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *RagChunkCreate) SetContent(v string) *RagChunkCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetEmbeddingContent sets the "embedding_content" field.
func (_c *RagChunkCreate) SetEmbeddingContent(v string) *RagChunkCreate {
	_c.mutation.SetEmbeddingContent(v)
	return _c
}

// SetHeadingPath sets the "heading_path" field.
func (_c *RagChunkCreate) SetHeadingPath(v []string) *RagChunkCreate {
	_c.mutation.SetHeadingPath(v)
	return _c
}

// SetStartLine sets the "start_line" field.
func (_c *RagChunkCreate) SetStartLine(v int) *RagChunkCreate {
	_c.mutation.SetStartLine(v)
	return _c
}

// SetEndLine sets the "end_line" field.
func (_c *RagChunkCreate) SetEndLine(v int) *RagChunkCreate {
	_c.mutation.SetEndLine(v)
	return _c
}

// SetEstimatedTokens sets the "estimated_tokens" field.
func (_c *RagChunkCreate) SetEstimatedTokens(v int) *RagChunkCreate {
	_c.mutation.SetEstimatedTokens(v)
	return _c
}

// SetContentHash sets the "content_hash" field.
func (_c *RagChunkCreate) SetContentHash(v string) *RagChunkCreate {
	_c.mutation.SetContentHash(v)
	return _c
}

// SetEmbedding sets the "embedding" field.
func (_c *RagChunkCreate) SetEmbedding(v pgvector.Vector) *RagChunkCreate {
	_c.mutation.SetEmbedding(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RagChunkCreate) SetCreatedAt(v time.Time) *RagChunkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RagChunkCreate) SetNillableCreatedAt(v *time.Time) *RagChunkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RagChunkCreate) SetID(v int64) *RagChunkCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetDocumentVersion sets the "document_version" edge to the RagDocumentVersion entity.
func (_c *RagChunkCreate) SetDocumentVersion(v *RagDocumentVersion) *RagChunkCreate {
	return _c.SetDocumentVersionID(v.ID)
}

// Mutation returns the RagChunkMutation object of the builder.
func (_c *RagChunkCreate) Mutation() *RagChunkMutation {
	return _c.mutation
}

// Save creates the RagChunk in the database.
func (_c *RagChunkCreate) Save(ctx context.Context) (*RagChunk, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RagChunkCreate) SaveX(ctx context.Context) *RagChunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RagChunkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RagChunkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RagChunkCreate) defaults() {
	if _, ok := _c.mutation.HeadingPath(); !ok {
		v := ragchunk.DefaultHeadingPath
		_c.mutation.SetHeadingPath(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ragchunk.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RagChunkCreate) check() error {
	if _, ok := _c.mutation.DocumentVersionID(); !ok {
		return &ValidationError{Name: "document_version_id", err: errors.New(`ent: missing required field "RagChunk.document_version_id"`)}
	}
	if _, ok := _c.mutation.ChunkIndex(); !ok {
		return &ValidationError{Name: "chunk_index", err: errors.New(`ent: missing required field "RagChunk.chunk_index"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "RagChunk.content"`)}
	}
	if _, ok := _c.mutation.EmbeddingContent(); !ok {
		return &ValidationError{Name: "embedding_content", err: errors.New(`ent: missing required field "RagChunk.embedding_content"`)}
	}
	if _, ok := _c.mutation.HeadingPath(); !ok {
		return &ValidationError{Name: "heading_path", err: errors.New(`ent: missing required field "RagChunk.heading_path"`)}
	}
	if _, ok := _c.mutation.StartLine(); !ok {
		return &ValidationError{Name: "start_line", err: errors.New(`ent: missing required field "RagChunk.start_line"`)}
	}
	if _, ok := _c.mutation.EndLine(); !ok {
		return &ValidationError{Name: "end_line", err: errors.New(`ent: missing required field "RagChunk.end_line"`)}
	}
	if _, ok := _c.mutation.EstimatedTokens(); !ok {
		return &ValidationError{Name: "estimated_tokens", err: errors.New(`ent: missing required field "RagChunk.estimated_tokens"`)}
	}
	if _, ok := _c.mutation.ContentHash(); !ok {
		return &ValidationError{Name: "content_hash", err: errors.New(`ent: missing required field "RagChunk.content_hash"`)}
	}
	if _, ok := _c.mutation.Embedding(); !ok {
		return &ValidationError{Name: "embedding", err: errors.New(`ent: missing required field "RagChunk.embedding"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RagChunk.created_at"`)}
	}
	if len(_c.mutation.DocumentVersionIDs()) == 0 {
		return &ValidationError{Name: "document_version", err: errors.New(`ent: missing required edge "RagChunk.document_version"`)}
	}
	return nil
}

func (_c *RagChunkCreate) sqlSave(ctx context.Context) (*RagChunk, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RagChunkCreate) createSpec() (*RagChunk, *sqlgraph.CreateSpec) {
	var (
		_node = &RagChunk{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ragchunk.Table, sqlgraph.NewFieldSpec(ragchunk.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ChunkIndex(); ok {
		_spec.SetField(ragchunk.FieldChunkIndex, field.TypeInt, value)
		_node.ChunkIndex = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(ragchunk.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.EmbeddingContent(); ok {
		_spec.SetField(ragchunk.FieldEmbeddingContent, field.TypeString, value)
		_node.EmbeddingContent = value
	}
	if value, ok := _c.mutation.HeadingPath(); ok {
		_spec.SetField(ragchunk.FieldHeadingPath, field.TypeJSON, value)
		_node.HeadingPath = value
	}
	if value, ok := _c.mutation.StartLine(); ok {
		_spec.SetField(ragchunk.FieldStartLine, field.TypeInt, value)
		_node.StartLine = value
	}
	if value, ok := _c.mutation.EndLine(); ok {
		_spec.SetField(ragchunk.FieldEndLine, field.TypeInt, value)
		_node.EndLine = value
	}
	if value, ok := _c.mutation.EstimatedTokens(); ok {
		_spec.SetField(ragchunk.FieldEstimatedTokens, field.TypeInt, value)
		_node.EstimatedTokens = value
	}
	if value, ok := _c.mutation.ContentHash(); ok {
		_spec.SetField(ragchunk.FieldContentHash, field.TypeString, value)
		_node.ContentHash = value
	}
	if value, ok := _c.mutation.Embedding(); ok {
		_spec.SetField(ragchunk.FieldEmbedding, field.TypeOther, value)
		_node.Embedding = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ragchunk.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.DocumentVersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ragchunk.DocumentVersionTable,
			Columns: []string{ragchunk.DocumentVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ragdocumentversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DocumentVersionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RagChunk.Create().
//		SetDocumentVersionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RagChunkUpsert) {
//			SetDocumentVersionID(v+v).
//		}).
//		Exec(ctx)
func (_c *RagChunkCreate) OnConflict(opts ...sql.ConflictOption) *RagChunkUpsertOne {
	_c.conflict = opts
	return &RagChunkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RagChunk.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RagChunkCreate) OnConflictColumns(columns ...string) *RagChunkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RagChunkUpsertOne{
		create: _c,
	}
}

type (
	// RagChunkUpsertOne is the builder for "upsert"-ing
	//  one RagChunk node.
	RagChunkUpsertOne struct {
		create *RagChunkCreate
	}

	// RagChunkUpsert is the "OnConflict" setter.
	RagChunkUpsert struct {
		*sql.UpdateSet
	}
)

// SetDocumentVersionID sets the "document_version_id" field.
func (u *RagChunkUpsert) SetDocumentVersionID(v int64) *RagChunkUpsert {
	u.Set(ragchunk.FieldDocumentVersionID, v)
	return u
}

// UpdateDocumentVersionID sets the "document_version_id" field to the value that was provided on create.
func (u *RagChunkUpsert) UpdateDocumentVersionID() *RagChunkUpsert {
	u.SetExcluded(ragchunk.FieldDocumentVersionID)
	return u
}

// SetChunkIndex sets the "chunk_index" field.
func (u *RagChunkUpsert) SetChunkIndex(v int) *RagChunkUpsert {
	u.Set(ragchunk.FieldChunkIndex, v)
	return u
}

// UpdateChunkIndex sets the "chunk_index" field to the value that was provided on create.
func (u *RagChunkUpsert) UpdateChunkIndex() *RagChunkUpsert {
	u.SetExcluded(ragchunk.FieldChunkIndex)
	return u
}

// AddChunkIndex adds v to the "chunk_index" field.
func (u *RagChunkUpsert) AddChunkIndex(v int) *RagChunkUpsert {
	u.Add(ragchunk.FieldChunkIndex, v)
	return u
}

// SetContent sets the "content" field.
func (u *RagChunkUpsert) SetContent(v string) *RagChunkUpsert {
	u.Set(ragchunk.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *RagChunkUpsert) UpdateContent() *RagChunkUpsert {
	u.SetExcluded(ragchunk.FieldContent)
	return u
}

// SetEmbeddingContent sets the "embedding_content" field.
func (u *RagChunkUpsert) SetEmbeddingContent(v string) *RagChunkUpsert {
	u.Set(ragchunk.FieldEmbeddingContent, v)
	return u
}

// UpdateEmbeddingContent sets the "embedding_content" field to the value that was provided on create.
func (u *RagChunkUpsert) UpdateEmbeddingContent() *RagChunkUpsert {
	u.SetExcluded(ragchunk.FieldEmbeddingContent)
	return u
}

// SetHeadingPath sets the "heading_path" field.
func (u *RagChunkUpsert) SetHeadingPath(v []string) *RagChunkUpsert {
	u.Set(ragchunk.FieldHeadingPath, v)
	return u
}

// UpdateHeadingPath sets the "heading_path" field to the value that was provided on create.
func (u *RagChunkUpsert) UpdateHeadingPath() *RagChunkUpsert {
	u.SetExcluded(ragchunk.FieldHeadingPath)
	return u
}

// SetStartLine sets the "start_line" field.
func (u *RagChunkUpsert) SetStartLine(v int) *RagChunkUpsert {
	u.Set(ragchunk.FieldStartLine, v)
	return u
}

// UpdateStartLine sets the "start_line" field to the value that was provided on create.
func (u *RagChunkUpsert) UpdateStartLine() *RagChunkUpsert {
	u.SetExcluded(ragchunk.FieldStartLine)
	return u
}

// AddStartLine adds v to the "start_line" field.
func (u *RagChunkUpsert) AddStartLine(v int) *RagChunkUpsert {
	u.Add(ragchunk.FieldStartLine, v)
	return u
}

// SetEndLine sets the "end_line" field.
func (u *RagChunkUpsert) SetEndLine(v int) *RagChunkUpsert {
	u.Set(ragchunk.FieldEndLine, v)
	return u
}

// UpdateEndLine sets the "end_line" field to the value that was provided on create.
func (u *RagChunkUpsert) UpdateEndLine() *RagChunkUpsert {
	u.SetExcluded(ragchunk.FieldEndLine)
	return u
}

// AddEndLine adds v to the "end_line" field.
func (u *RagChunkUpsert) AddEndLine(v int) *RagChunkUpsert {
	u.Add(ragchunk.FieldEndLine, v)
	return u
}

// SetEstimatedTokens sets the "estimated_tokens" field.
func (u *RagChunkUpsert) SetEstimatedTokens(v int) *RagChunkUpsert {
	u.Set(ragchunk.FieldEstimatedTokens, v)
	return u
}

// UpdateEstimatedTokens sets the "estimated_tokens" field to the value that was provided on create.
func (u *RagChunkUpsert) UpdateEstimatedTokens() *RagChunkUpsert {
	u.SetExcluded(ragchunk.FieldEstimatedTokens)
	return u
}

// AddEstimatedTokens adds v to the "estimated_tokens" field.
func (u *RagChunkUpsert) AddEstimatedTokens(v int) *RagChunkUpsert {
	u.Add(ragchunk.FieldEstimatedTokens, v)
	return u
}

// SetContentHash sets the "content_hash" field.
func (u *RagChunkUpsert) SetContentHash(v string) *RagChunkUpsert {
	u.Set(ragchunk.FieldContentHash, v)
	return u
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *RagChunkUpsert) UpdateContentHash() *RagChunkUpsert {
	u.SetExcluded(ragchunk.FieldContentHash)
	return u
}

// SetEmbedding sets the "embedding" field.
func (u *RagChunkUpsert) SetEmbedding(v pgvector.Vector) *RagChunkUpsert {
	u.Set(ragchunk.FieldEmbedding, v)
	return u
}

// UpdateEmbedding sets the "embedding" field to the value that was provided on create.
func (u *RagChunkUpsert) UpdateEmbedding() *RagChunkUpsert {
	u.SetExcluded(ragchunk.FieldEmbedding)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RagChunk.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ragchunk.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RagChunkUpsertOne) UpdateNewValues() *RagChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ragchunk.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ragchunk.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RagChunk.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RagChunkUpsertOne) Ignore() *RagChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RagChunkUpsertOne) DoNothing() *RagChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RagChunkCreate.OnConflict
// documentation for more info.
func (u *RagChunkUpsertOne) Update(set func(*RagChunkUpsert)) *RagChunkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RagChunkUpsert{UpdateSet: update})
	}))
	return u
}

// SetDocumentVersionID sets the "document_version_id" field.
func (u *RagChunkUpsertOne) SetDocumentVersionID(v int64) *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetDocumentVersionID(v)
	})
}

// UpdateDocumentVersionID sets the "document_version_id" field to the value that was provided on create.
func (u *RagChunkUpsertOne) UpdateDocumentVersionID() *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateDocumentVersionID()
	})
}

// SetChunkIndex sets the "chunk_index" field.
func (u *RagChunkUpsertOne) SetChunkIndex(v int) *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetChunkIndex(v)
	})
}

// AddChunkIndex adds v to the "chunk_index" field.
func (u *RagChunkUpsertOne) AddChunkIndex(v int) *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.AddChunkIndex(v)
	})
}

// UpdateChunkIndex sets the "chunk_index" field to the value that was provided on create.
func (u *RagChunkUpsertOne) UpdateChunkIndex() *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateChunkIndex()
	})
}

// SetContent sets the "content" field.
func (u *RagChunkUpsertOne) SetContent(v string) *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *RagChunkUpsertOne) UpdateContent() *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateContent()
	})
}

// SetEmbeddingContent sets the "embedding_content" field.
func (u *RagChunkUpsertOne) SetEmbeddingContent(v string) *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetEmbeddingContent(v)
	})
}

// UpdateEmbeddingContent sets the "embedding_content" field to the value that was provided on create.
func (u *RagChunkUpsertOne) UpdateEmbeddingContent() *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateEmbeddingContent()
	})
}

// SetHeadingPath sets the "heading_path" field.
func (u *RagChunkUpsertOne) SetHeadingPath(v []string) *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetHeadingPath(v)
	})
}

// UpdateHeadingPath sets the "heading_path" field to the value that was provided on create.
func (u *RagChunkUpsertOne) UpdateHeadingPath() *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateHeadingPath()
	})
}

// SetStartLine sets the "start_line" field.
func (u *RagChunkUpsertOne) SetStartLine(v int) *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetStartLine(v)
	})
}

// AddStartLine adds v to the "start_line" field.
func (u *RagChunkUpsertOne) AddStartLine(v int) *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.AddStartLine(v)
	})
}

// UpdateStartLine sets the "start_line" field to the value that was provided on create.
func (u *RagChunkUpsertOne) UpdateStartLine() *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateStartLine()
	})
}

// SetEndLine sets the "end_line" field.
func (u *RagChunkUpsertOne) SetEndLine(v int) *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetEndLine(v)
	})
}

// AddEndLine adds v to the "end_line" field.
func (u *RagChunkUpsertOne) AddEndLine(v int) *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.AddEndLine(v)
	})
}

// UpdateEndLine sets the "end_line" field to the value that was provided on create.
func (u *RagChunkUpsertOne) UpdateEndLine() *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateEndLine()
	})
}

// SetEstimatedTokens sets the "estimated_tokens" field.
func (u *RagChunkUpsertOne) SetEstimatedTokens(v int) *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetEstimatedTokens(v)
	})
}

// AddEstimatedTokens adds v to the "estimated_tokens" field.
func (u *RagChunkUpsertOne) AddEstimatedTokens(v int) *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.AddEstimatedTokens(v)
	})
}

// UpdateEstimatedTokens sets the "estimated_tokens" field to the value that was provided on create.
func (u *RagChunkUpsertOne) UpdateEstimatedTokens() *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateEstimatedTokens()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *RagChunkUpsertOne) SetContentHash(v string) *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *RagChunkUpsertOne) UpdateContentHash() *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateContentHash()
	})
}

// SetEmbedding sets the "embedding" field.
func (u *RagChunkUpsertOne) SetEmbedding(v pgvector.Vector) *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetEmbedding(v)
	})
}

// UpdateEmbedding sets the "embedding" field to the value that was provided on create.
func (u *RagChunkUpsertOne) UpdateEmbedding() *RagChunkUpsertOne {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateEmbedding()
	})
}

// Exec executes the query.
func (u *RagChunkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RagChunkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RagChunkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RagChunkUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RagChunkUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RagChunkCreateBulk is the builder for creating many RagChunk entities in bulk.
type RagChunkCreateBulk struct {
	config
	err      error
	builders []*RagChunkCreate
	conflict []sql.ConflictOption
}

// Save creates the RagChunk entities in the database.
func (_c *RagChunkCreateBulk) Save(ctx context.Context) ([]*RagChunk, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RagChunk, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RagChunkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RagChunkCreateBulk) SaveX(ctx context.Context) []*RagChunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RagChunkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RagChunkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RagChunk.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RagChunkUpsert) {
//			SetDocumentVersionID(v+v).
//		}).
//		Exec(ctx)
func (_c *RagChunkCreateBulk) OnConflict(opts ...sql.ConflictOption) *RagChunkUpsertBulk {
	_c.conflict = opts
	return &RagChunkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RagChunk.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RagChunkCreateBulk) OnConflictColumns(columns ...string) *RagChunkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RagChunkUpsertBulk{
		create: _c,
	}
}

// RagChunkUpsertBulk is the builder for "upsert"-ing
// a bulk of RagChunk nodes.
type RagChunkUpsertBulk struct {
	create *RagChunkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RagChunk.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ragchunk.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RagChunkUpsertBulk) UpdateNewValues() *RagChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ragchunk.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ragchunk.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RagChunk.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RagChunkUpsertBulk) Ignore() *RagChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RagChunkUpsertBulk) DoNothing() *RagChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RagChunkCreateBulk.OnConflict
// documentation for more info.
func (u *RagChunkUpsertBulk) Update(set func(*RagChunkUpsert)) *RagChunkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RagChunkUpsert{UpdateSet: update})
	}))
	return u
}

// SetDocumentVersionID sets the "document_version_id" field.
func (u *RagChunkUpsertBulk) SetDocumentVersionID(v int64) *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetDocumentVersionID(v)
	})
}

// UpdateDocumentVersionID sets the "document_version_id" field to the value that was provided on create.
func (u *RagChunkUpsertBulk) UpdateDocumentVersionID() *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateDocumentVersionID()
	})
}

// SetChunkIndex sets the "chunk_index" field.
func (u *RagChunkUpsertBulk) SetChunkIndex(v int) *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetChunkIndex(v)
	})
}

// AddChunkIndex adds v to the "chunk_index" field.
func (u *RagChunkUpsertBulk) AddChunkIndex(v int) *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.AddChunkIndex(v)
	})
}

// UpdateChunkIndex sets the "chunk_index" field to the value that was provided on create.
func (u *RagChunkUpsertBulk) UpdateChunkIndex() *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateChunkIndex()
	})
}

// SetContent sets the "content" field.
func (u *RagChunkUpsertBulk) SetContent(v string) *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *RagChunkUpsertBulk) UpdateContent() *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateContent()
	})
}

// SetEmbeddingContent sets the "embedding_content" field.
func (u *RagChunkUpsertBulk) SetEmbeddingContent(v string) *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetEmbeddingContent(v)
	})
}

// UpdateEmbeddingContent sets the "embedding_content" field to the value that was provided on create.
func (u *RagChunkUpsertBulk) UpdateEmbeddingContent() *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateEmbeddingContent()
	})
}

// SetHeadingPath sets the "heading_path" field.
func (u *RagChunkUpsertBulk) SetHeadingPath(v []string) *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetHeadingPath(v)
	})
}

// UpdateHeadingPath sets the "heading_path" field to the value that was provided on create.
func (u *RagChunkUpsertBulk) UpdateHeadingPath() *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateHeadingPath()
	})
}

// SetStartLine sets the "start_line" field.
func (u *RagChunkUpsertBulk) SetStartLine(v int) *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetStartLine(v)
	})
}

// AddStartLine adds v to the "start_line" field.
func (u *RagChunkUpsertBulk) AddStartLine(v int) *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.AddStartLine(v)
	})
}

// UpdateStartLine sets the "start_line" field to the value that was provided on create.
func (u *RagChunkUpsertBulk) UpdateStartLine() *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateStartLine()
	})
}

// SetEndLine sets the "end_line" field.
func (u *RagChunkUpsertBulk) SetEndLine(v int) *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetEndLine(v)
	})
}

// AddEndLine adds v to the "end_line" field.
func (u *RagChunkUpsertBulk) AddEndLine(v int) *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.AddEndLine(v)
	})
}

// UpdateEndLine sets the "end_line" field to the value that was provided on create.
func (u *RagChunkUpsertBulk) UpdateEndLine() *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateEndLine()
	})
}

// SetEstimatedTokens sets the "estimated_tokens" field.
func (u *RagChunkUpsertBulk) SetEstimatedTokens(v int) *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetEstimatedTokens(v)
	})
}

// AddEstimatedTokens adds v to the "estimated_tokens" field.
func (u *RagChunkUpsertBulk) AddEstimatedTokens(v int) *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.AddEstimatedTokens(v)
	})
}

// UpdateEstimatedTokens sets the "estimated_tokens" field to the value that was provided on create.
func (u *RagChunkUpsertBulk) UpdateEstimatedTokens() *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateEstimatedTokens()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *RagChunkUpsertBulk) SetContentHash(v string) *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *RagChunkUpsertBulk) UpdateContentHash() *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateContentHash()
	})
}

// SetEmbedding sets the "embedding" field.
func (u *RagChunkUpsertBulk) SetEmbedding(v pgvector.Vector) *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.SetEmbedding(v)
	})
}

// UpdateEmbedding sets the "embedding" field to the value that was provided on create.
func (u *RagChunkUpsertBulk) UpdateEmbedding() *RagChunkUpsertBulk {
	return u.Update(func(s *RagChunkUpsert) {
		s.UpdateEmbedding()
	})
}

// Exec executes the query.
func (u *RagChunkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RagChunkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RagChunkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RagChunkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
