// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/PolarishT/sales-agent/ent/predicate"
	"github.com/PolarishT/sales-agent/ent/ragchunk"
	"github.com/PolarishT/sales-agent/ent/ragdocumentversion"
	pgvector "github.com/pgvector/pgvector-go"
)

// RagChunkUpdate is the builder for updating RagChunk entities.
type RagChunkUpdate struct {
	config
	hooks    []Hook
	mutation *RagChunkMutation
}

// Where appends a list predicates to the RagChunkUpdate builder.
func (_u *RagChunkUpdate) Where(ps ...predicate.RagChunk) *RagChunkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDocumentVersionID sets the "document_version_id" field.
func (_u *RagChunkUpdate) SetDocumentVersionID(v int64) *RagChunkUpdate {
	_u.mutation.SetDocumentVersionID(v)
	return _u
}

// SetNillableDocumentVersionID sets the "document_version_id" field if the given value is not nil.
func (_u *RagChunkUpdate) SetNillableDocumentVersionID(v *int64) *RagChunkUpdate {
	if v != nil {
		_u.SetDocumentVersionID(*v)
	}
	return _u
}

// SetChunkIndex sets the "chunk_index" field.
func (_u *RagChunkUpdate) SetChunkIndex(v int) *RagChunkUpdate {
	_u.mutation.ResetChunkIndex()
	_u.mutation.SetChunkIndex(v)
	return _u
}

// SetNillableChunkIndex sets the "chunk_index" field if the given value is not nil.
func (_u *RagChunkUpdate) SetNillableChunkIndex(v *int) *RagChunkUpdate {
	if v != nil {
		_u.SetChunkIndex(*v)
	}
	return _u
}

// AddChunkIndex adds value to the "chunk_index" field.
func (_u *RagChunkUpdate) AddChunkIndex(v int) *RagChunkUpdate {
	_u.mutation.AddChunkIndex(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *RagChunkUpdate) SetContent(v string) *RagChunkUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *RagChunkUpdate) SetNillableContent(v *string) *RagChunkUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetEmbeddingContent sets the "embedding_content" field.
func (_u *RagChunkUpdate) SetEmbeddingContent(v string) *RagChunkUpdate {
	_u.mutation.SetEmbeddingContent(v)
	return _u
}

// SetNillableEmbeddingContent sets the "embedding_content" field if the given value is not nil.
func (_u *RagChunkUpdate) SetNillableEmbeddingContent(v *string) *RagChunkUpdate {
	if v != nil {
		_u.SetEmbeddingContent(*v)
	}
	return _u
}

// SetHeadingPath sets the "heading_path" field.
func (_u *RagChunkUpdate) SetHeadingPath(v []string) *RagChunkUpdate {
	_u.mutation.SetHeadingPath(v)
	return _u
}

// AppendHeadingPath appends value to the "heading_path" field.
func (_u *RagChunkUpdate) AppendHeadingPath(v []string) *RagChunkUpdate {
	_u.mutation.AppendHeadingPath(v)
	return _u
}

// SetStartLine sets the "start_line" field.
func (_u *RagChunkUpdate) SetStartLine(v int) *RagChunkUpdate {
	_u.mutation.ResetStartLine()
	_u.mutation.SetStartLine(v)
	return _u
}

// SetNillableStartLine sets the "start_line" field if the given value is not nil.
func (_u *RagChunkUpdate) SetNillableStartLine(v *int) *RagChunkUpdate {
	if v != nil {
		_u.SetStartLine(*v)
	}
	return _u
}

// AddStartLine adds value to the "start_line" field.
func (_u *RagChunkUpdate) AddStartLine(v int) *RagChunkUpdate {
	_u.mutation.AddStartLine(v)
	return _u
}

// SetEndLine sets the "end_line" field.
func (_u *RagChunkUpdate) SetEndLine(v int) *RagChunkUpdate {
	_u.mutation.ResetEndLine()
	_u.mutation.SetEndLine(v)
	return _u
}

// SetNillableEndLine sets the "end_line" field if the given value is not nil.
func (_u *RagChunkUpdate) SetNillableEndLine(v *int) *RagChunkUpdate {
	if v != nil {
		_u.SetEndLine(*v)
	}
	return _u
}

// AddEndLine adds value to the "end_line" field.
func (_u *RagChunkUpdate) AddEndLine(v int) *RagChunkUpdate {
	_u.mutation.AddEndLine(v)
	return _u
}

// SetEstimatedTokens sets the "estimated_tokens" field.
func (_u *RagChunkUpdate) SetEstimatedTokens(v int) *RagChunkUpdate {
	_u.mutation.ResetEstimatedTokens()
	_u.mutation.SetEstimatedTokens(v)
	return _u
}

// SetNillableEstimatedTokens sets the "estimated_tokens" field if the given value is not nil.
func (_u *RagChunkUpdate) SetNillableEstimatedTokens(v *int) *RagChunkUpdate {
	if v != nil {
		_u.SetEstimatedTokens(*v)
	}
	return _u
}

// AddEstimatedTokens adds value to the "estimated_tokens" field.
func (_u *RagChunkUpdate) AddEstimatedTokens(v int) *RagChunkUpdate {
	_u.mutation.AddEstimatedTokens(v)
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *RagChunkUpdate) SetContentHash(v string) *RagChunkUpdate {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *RagChunkUpdate) SetNillableContentHash(v *string) *RagChunkUpdate {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *RagChunkUpdate) SetEmbedding(v pgvector.Vector) *RagChunkUpdate {
	_u.mutation.SetEmbedding(v)
	return _u
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (_u *RagChunkUpdate) SetNillableEmbedding(v *pgvector.Vector) *RagChunkUpdate {
	if v != nil {
		_u.SetEmbedding(*v)
	}
	return _u
}

// SetDocumentVersion sets the "document_version" edge to the RagDocumentVersion entity.
func (_u *RagChunkUpdate) SetDocumentVersion(v *RagDocumentVersion) *RagChunkUpdate {
	return _u.SetDocumentVersionID(v.ID)
}

// Mutation returns the RagChunkMutation object of the builder.
func (_u *RagChunkUpdate) Mutation() *RagChunkMutation {
	return _u.mutation
}

// ClearDocumentVersion clears the "document_version" edge to the RagDocumentVersion entity.
func (_u *RagChunkUpdate) ClearDocumentVersion() *RagChunkUpdate {
	_u.mutation.ClearDocumentVersion()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RagChunkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RagChunkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RagChunkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RagChunkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RagChunkUpdate) check() error {
	if _u.mutation.DocumentVersionCleared() && len(_u.mutation.DocumentVersionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RagChunk.document_version"`)
	}
	return nil
}

func (_u *RagChunkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ragchunk.Table, ragchunk.Columns, sqlgraph.NewFieldSpec(ragchunk.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChunkIndex(); ok {
		_spec.SetField(ragchunk.FieldChunkIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChunkIndex(); ok {
		_spec.AddField(ragchunk.FieldChunkIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(ragchunk.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmbeddingContent(); ok {
		_spec.SetField(ragchunk.FieldEmbeddingContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeadingPath(); ok {
		_spec.SetField(ragchunk.FieldHeadingPath, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedHeadingPath(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, ragchunk.FieldHeadingPath, value)
		})
	}
	if value, ok := _u.mutation.StartLine(); ok {
		_spec.SetField(ragchunk.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartLine(); ok {
		_spec.AddField(ragchunk.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EndLine(); ok {
		_spec.SetField(ragchunk.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndLine(); ok {
		_spec.AddField(ragchunk.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EstimatedTokens(); ok {
		_spec.SetField(ragchunk.FieldEstimatedTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedTokens(); ok {
		_spec.AddField(ragchunk.FieldEstimatedTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(ragchunk.FieldContentHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(ragchunk.FieldEmbedding, field.TypeOther, value)
	}
	if _u.mutation.DocumentVersionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ragchunk.DocumentVersionTable,
			Columns: []string{ragchunk.DocumentVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ragdocumentversion.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentVersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ragchunk.DocumentVersionTable,
			Columns: []string{ragchunk.DocumentVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ragdocumentversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ragchunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RagChunkUpdateOne is the builder for updating a single RagChunk entity.
type RagChunkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RagChunkMutation
}

// SetDocumentVersionID sets the "document_version_id" field.
func (_u *RagChunkUpdateOne) SetDocumentVersionID(v int64) *RagChunkUpdateOne {
	_u.mutation.SetDocumentVersionID(v)
	return _u
}

// SetNillableDocumentVersionID sets the "document_version_id" field if the given value is not nil.
func (_u *RagChunkUpdateOne) SetNillableDocumentVersionID(v *int64) *RagChunkUpdateOne {
	if v != nil {
		_u.SetDocumentVersionID(*v)
	}
	return _u
}

// SetChunkIndex sets the "chunk_index" field.
func (_u *RagChunkUpdateOne) SetChunkIndex(v int) *RagChunkUpdateOne {
	_u.mutation.ResetChunkIndex()
	_u.mutation.SetChunkIndex(v)
	return _u
}

// SetNillableChunkIndex sets the "chunk_index" field if the given value is not nil.
func (_u *RagChunkUpdateOne) SetNillableChunkIndex(v *int) *RagChunkUpdateOne {
	if v != nil {
		_u.SetChunkIndex(*v)
	}
	return _u
}

// AddChunkIndex adds value to the "chunk_index" field.
func (_u *RagChunkUpdateOne) AddChunkIndex(v int) *RagChunkUpdateOne {
	_u.mutation.AddChunkIndex(v)
	return _u
}

// SetContent sets the "content" field.
func (_u *RagChunkUpdateOne) SetContent(v string) *RagChunkUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *RagChunkUpdateOne) SetNillableContent(v *string) *RagChunkUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetEmbeddingContent sets the "embedding_content" field.
func (_u *RagChunkUpdateOne) SetEmbeddingContent(v string) *RagChunkUpdateOne {
	_u.mutation.SetEmbeddingContent(v)
	return _u
}

// SetNillableEmbeddingContent sets the "embedding_content" field if the given value is not nil.
func (_u *RagChunkUpdateOne) SetNillableEmbeddingContent(v *string) *RagChunkUpdateOne {
	if v != nil {
		_u.SetEmbeddingContent(*v)
	}
	return _u
}

// SetHeadingPath sets the "heading_path" field.
func (_u *RagChunkUpdateOne) SetHeadingPath(v []string) *RagChunkUpdateOne {
	_u.mutation.SetHeadingPath(v)
	return _u
}

// AppendHeadingPath appends value to the "heading_path" field.
func (_u *RagChunkUpdateOne) AppendHeadingPath(v []string) *RagChunkUpdateOne {
	_u.mutation.AppendHeadingPath(v)
	return _u
}

// SetStartLine sets the "start_line" field.
func (_u *RagChunkUpdateOne) SetStartLine(v int) *RagChunkUpdateOne {
	_u.mutation.ResetStartLine()
	_u.mutation.SetStartLine(v)
	return _u
}

// SetNillableStartLine sets the "start_line" field if the given value is not nil.
func (_u *RagChunkUpdateOne) SetNillableStartLine(v *int) *RagChunkUpdateOne {
	if v != nil {
		_u.SetStartLine(*v)
	}
	return _u
}

// AddStartLine adds value to the "start_line" field.
func (_u *RagChunkUpdateOne) AddStartLine(v int) *RagChunkUpdateOne {
	_u.mutation.AddStartLine(v)
	return _u
}

// SetEndLine sets the "end_line" field.
func (_u *RagChunkUpdateOne) SetEndLine(v int) *RagChunkUpdateOne {
	_u.mutation.ResetEndLine()
	_u.mutation.SetEndLine(v)
	return _u
}

// SetNillableEndLine sets the "end_line" field if the given value is not nil.
func (_u *RagChunkUpdateOne) SetNillableEndLine(v *int) *RagChunkUpdateOne {
	if v != nil {
		_u.SetEndLine(*v)
	}
	return _u
}

// AddEndLine adds value to the "end_line" field.
func (_u *RagChunkUpdateOne) AddEndLine(v int) *RagChunkUpdateOne {
	_u.mutation.AddEndLine(v)
	return _u
}

// SetEstimatedTokens sets the "estimated_tokens" field.
func (_u *RagChunkUpdateOne) SetEstimatedTokens(v int) *RagChunkUpdateOne {
	_u.mutation.ResetEstimatedTokens()
	_u.mutation.SetEstimatedTokens(v)
	return _u
}

// SetNillableEstimatedTokens sets the "estimated_tokens" field if the given value is not nil.
func (_u *RagChunkUpdateOne) SetNillableEstimatedTokens(v *int) *RagChunkUpdateOne {
	if v != nil {
		_u.SetEstimatedTokens(*v)
	}
	return _u
}

// AddEstimatedTokens adds value to the "estimated_tokens" field.
func (_u *RagChunkUpdateOne) AddEstimatedTokens(v int) *RagChunkUpdateOne {
	_u.mutation.AddEstimatedTokens(v)
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *RagChunkUpdateOne) SetContentHash(v string) *RagChunkUpdateOne {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *RagChunkUpdateOne) SetNillableContentHash(v *string) *RagChunkUpdateOne {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetEmbedding sets the "embedding" field.
func (_u *RagChunkUpdateOne) SetEmbedding(v pgvector.Vector) *RagChunkUpdateOne {
	_u.mutation.SetEmbedding(v)
	return _u
}

// SetNillableEmbedding sets the "embedding" field if the given value is not nil.
func (_u *RagChunkUpdateOne) SetNillableEmbedding(v *pgvector.Vector) *RagChunkUpdateOne {
	if v != nil {
		_u.SetEmbedding(*v)
	}
	return _u
}

// SetDocumentVersion sets the "document_version" edge to the RagDocumentVersion entity.
func (_u *RagChunkUpdateOne) SetDocumentVersion(v *RagDocumentVersion) *RagChunkUpdateOne {
	return _u.SetDocumentVersionID(v.ID)
}

// Mutation returns the RagChunkMutation object of the builder.
func (_u *RagChunkUpdateOne) Mutation() *RagChunkMutation {
	return _u.mutation
}

// ClearDocumentVersion clears the "document_version" edge to the RagDocumentVersion entity.
func (_u *RagChunkUpdateOne) ClearDocumentVersion() *RagChunkUpdateOne {
	_u.mutation.ClearDocumentVersion()
	return _u
}

// Where appends a list predicates to the RagChunkUpdate builder.
func (_u *RagChunkUpdateOne) Where(ps ...predicate.RagChunk) *RagChunkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RagChunkUpdateOne) Select(field string, fields ...string) *RagChunkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RagChunk entity.
func (_u *RagChunkUpdateOne) Save(ctx context.Context) (*RagChunk, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RagChunkUpdateOne) SaveX(ctx context.Context) *RagChunk {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RagChunkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RagChunkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RagChunkUpdateOne) check() error {
	if _u.mutation.DocumentVersionCleared() && len(_u.mutation.DocumentVersionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RagChunk.document_version"`)
	}
	return nil
}

func (_u *RagChunkUpdateOne) sqlSave(ctx context.Context) (_node *RagChunk, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ragchunk.Table, ragchunk.Columns, sqlgraph.NewFieldSpec(ragchunk.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RagChunk.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ragchunk.FieldID)
		for _, f := range fields {
			if !ragchunk.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ragchunk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChunkIndex(); ok {
		_spec.SetField(ragchunk.FieldChunkIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChunkIndex(); ok {
		_spec.AddField(ragchunk.FieldChunkIndex, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(ragchunk.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmbeddingContent(); ok {
		_spec.SetField(ragchunk.FieldEmbeddingContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeadingPath(); ok {
		_spec.SetField(ragchunk.FieldHeadingPath, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedHeadingPath(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, ragchunk.FieldHeadingPath, value)
		})
	}
	if value, ok := _u.mutation.StartLine(); ok {
		_spec.SetField(ragchunk.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStartLine(); ok {
		_spec.AddField(ragchunk.FieldStartLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EndLine(); ok {
		_spec.SetField(ragchunk.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEndLine(); ok {
		_spec.AddField(ragchunk.FieldEndLine, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EstimatedTokens(); ok {
		_spec.SetField(ragchunk.FieldEstimatedTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEstimatedTokens(); ok {
		_spec.AddField(ragchunk.FieldEstimatedTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(ragchunk.FieldContentHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Embedding(); ok {
		_spec.SetField(ragchunk.FieldEmbedding, field.TypeOther, value)
	}
	if _u.mutation.DocumentVersionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ragchunk.DocumentVersionTable,
			Columns: []string{ragchunk.DocumentVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ragdocumentversion.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DocumentVersionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ragchunk.DocumentVersionTable,
			Columns: []string{ragchunk.DocumentVersionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ragdocumentversion.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RagChunk{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ragchunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
