// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PolarishT/sales-agent/ent/predicate"
	"github.com/PolarishT/sales-agent/ent/ragchunk"
	"github.com/PolarishT/sales-agent/ent/ragdocument"
	"github.com/PolarishT/sales-agent/ent/ragdocumentversion"
)

// RagDocumentVersionQuery is the builder for querying RagDocumentVersion entities.
type RagDocumentVersionQuery struct {
	config
	ctx          *QueryContext
	order        []ragdocumentversion.OrderOption
	inters       []Interceptor
	predicates   []predicate.RagDocumentVersion
	withDocument *RagDocumentQuery
	withChunks   *RagChunkQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RagDocumentVersionQuery builder.
func (_q *RagDocumentVersionQuery) Where(ps ...predicate.RagDocumentVersion) *RagDocumentVersionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RagDocumentVersionQuery) Limit(limit int) *RagDocumentVersionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RagDocumentVersionQuery) Offset(offset int) *RagDocumentVersionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RagDocumentVersionQuery) Unique(unique bool) *RagDocumentVersionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RagDocumentVersionQuery) Order(o ...ragdocumentversion.OrderOption) *RagDocumentVersionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDocument chains the current query on the "document" edge.
func (_q *RagDocumentVersionQuery) QueryDocument() *RagDocumentQuery {
	query := (&RagDocumentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ragdocumentversion.Table, ragdocumentversion.FieldID, selector),
			sqlgraph.To(ragdocument.Table, ragdocument.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ragdocumentversion.DocumentTable, ragdocumentversion.DocumentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChunks chains the current query on the "chunks" edge.
func (_q *RagDocumentVersionQuery) QueryChunks() *RagChunkQuery {
	query := (&RagChunkClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ragdocumentversion.Table, ragdocumentversion.FieldID, selector),
			sqlgraph.To(ragchunk.Table, ragchunk.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ragdocumentversion.ChunksTable, ragdocumentversion.ChunksColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RagDocumentVersion entity from the query.
// Returns a *NotFoundError when no RagDocumentVersion was found.
func (_q *RagDocumentVersionQuery) First(ctx context.Context) (*RagDocumentVersion, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ragdocumentversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RagDocumentVersionQuery) FirstX(ctx context.Context) *RagDocumentVersion {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RagDocumentVersion ID from the query.
// Returns a *NotFoundError when no RagDocumentVersion ID was found.
func (_q *RagDocumentVersionQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ragdocumentversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RagDocumentVersionQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RagDocumentVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RagDocumentVersion entity is found.
// Returns a *NotFoundError when no RagDocumentVersion entities are found.
func (_q *RagDocumentVersionQuery) Only(ctx context.Context) (*RagDocumentVersion, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ragdocumentversion.Label}
	default:
		return nil, &NotSingularError{ragdocumentversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RagDocumentVersionQuery) OnlyX(ctx context.Context) *RagDocumentVersion {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RagDocumentVersion ID in the query.
// Returns a *NotSingularError when more than one RagDocumentVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RagDocumentVersionQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ragdocumentversion.Label}
	default:
		err = &NotSingularError{ragdocumentversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RagDocumentVersionQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RagDocumentVersions.
func (_q *RagDocumentVersionQuery) All(ctx context.Context) ([]*RagDocumentVersion, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RagDocumentVersion, *RagDocumentVersionQuery]()
	return withInterceptors[[]*RagDocumentVersion](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RagDocumentVersionQuery) AllX(ctx context.Context) []*RagDocumentVersion {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RagDocumentVersion IDs.
func (_q *RagDocumentVersionQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(ragdocumentversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RagDocumentVersionQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RagDocumentVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RagDocumentVersionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RagDocumentVersionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RagDocumentVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RagDocumentVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RagDocumentVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RagDocumentVersionQuery) Clone() *RagDocumentVersionQuery {
	if _q == nil {
		return nil
	}
	return &RagDocumentVersionQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]ragdocumentversion.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.RagDocumentVersion{}, _q.predicates...),
		withDocument: _q.withDocument.Clone(),
		withChunks:   _q.withChunks.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithDocument tells the query-builder to eager-load the nodes that are connected to
// the "document" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RagDocumentVersionQuery) WithDocument(opts ...func(*RagDocumentQuery)) *RagDocumentVersionQuery {
	query := (&RagDocumentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDocument = query
	return _q
}

// WithChunks tells the query-builder to eager-load the nodes that are connected to
// the "chunks" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RagDocumentVersionQuery) WithChunks(opts ...func(*RagChunkQuery)) *RagDocumentVersionQuery {
	query := (&RagChunkClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChunks = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IngestionID uuid.UUID `json:"ingestion_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RagDocumentVersion.Query().
//		GroupBy(ragdocumentversion.FieldIngestionID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RagDocumentVersionQuery) GroupBy(field string, fields ...string) *RagDocumentVersionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RagDocumentVersionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = ragdocumentversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IngestionID uuid.UUID `json:"ingestion_id,omitempty"`
//	}
//
//	client.RagDocumentVersion.Query().
//		Select(ragdocumentversion.FieldIngestionID).
//		Scan(ctx, &v)
func (_q *RagDocumentVersionQuery) Select(fields ...string) *RagDocumentVersionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RagDocumentVersionSelect{RagDocumentVersionQuery: _q}
	sbuild.label = ragdocumentversion.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RagDocumentVersionSelect configured with the given aggregations.
func (_q *RagDocumentVersionQuery) Aggregate(fns ...AggregateFunc) *RagDocumentVersionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RagDocumentVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !ragdocumentversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RagDocumentVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RagDocumentVersion, error) {
	var (
		nodes       = []*RagDocumentVersion{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withDocument != nil,
			_q.withChunks != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RagDocumentVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RagDocumentVersion{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDocument; query != nil {
		if err := _q.loadDocument(ctx, query, nodes, nil,
			func(n *RagDocumentVersion, e *RagDocument) { n.Edges.Document = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChunks; query != nil {
		if err := _q.loadChunks(ctx, query, nodes,
			func(n *RagDocumentVersion) { n.Edges.Chunks = []*RagChunk{} },
			func(n *RagDocumentVersion, e *RagChunk) { n.Edges.Chunks = append(n.Edges.Chunks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RagDocumentVersionQuery) loadDocument(ctx context.Context, query *RagDocumentQuery, nodes []*RagDocumentVersion, init func(*RagDocumentVersion), assign func(*RagDocumentVersion, *RagDocument)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*RagDocumentVersion)
	for i := range nodes {
		fk := nodes[i].DocumentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(ragdocument.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "document_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RagDocumentVersionQuery) loadChunks(ctx context.Context, query *RagChunkQuery, nodes []*RagDocumentVersion, init func(*RagDocumentVersion), assign func(*RagDocumentVersion, *RagChunk)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RagDocumentVersion)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ragchunk.FieldDocumentVersionID)
	}
	query.Where(predicate.RagChunk(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(ragdocumentversion.ChunksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DocumentVersionID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "document_version_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *RagDocumentVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RagDocumentVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ragdocumentversion.Table, ragdocumentversion.Columns, sqlgraph.NewFieldSpec(ragdocumentversion.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ragdocumentversion.FieldID)
		for i := range fields {
			if fields[i] != ragdocumentversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withDocument != nil {
			_spec.Node.AddColumnOnce(ragdocumentversion.FieldDocumentID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RagDocumentVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(ragdocumentversion.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = ragdocumentversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *RagDocumentVersionQuery) ForUpdate(opts ...sql.LockOption) *RagDocumentVersionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *RagDocumentVersionQuery) ForShare(opts ...sql.LockOption) *RagDocumentVersionQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// RagDocumentVersionGroupBy is the group-by builder for RagDocumentVersion entities.
type RagDocumentVersionGroupBy struct {
	selector
	build *RagDocumentVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RagDocumentVersionGroupBy) Aggregate(fns ...AggregateFunc) *RagDocumentVersionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RagDocumentVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RagDocumentVersionQuery, *RagDocumentVersionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RagDocumentVersionGroupBy) sqlScan(ctx context.Context, root *RagDocumentVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RagDocumentVersionSelect is the builder for selecting fields of RagDocumentVersion entities.
type RagDocumentVersionSelect struct {
	*RagDocumentVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RagDocumentVersionSelect) Aggregate(fns ...AggregateFunc) *RagDocumentVersionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RagDocumentVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RagDocumentVersionQuery, *RagDocumentVersionSelect](ctx, _s.RagDocumentVersionQuery, _s, _s.inters, v)
}

func (_s *RagDocumentVersionSelect) sqlScan(ctx context.Context, root *RagDocumentVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
