// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/PolarishT/sales-agent/ent/ragdocument"
)

// RagDocument is the model entity for the RagDocument schema.
type RagDocument struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// DocumentKey holds the value of the "document_key" field.
	DocumentKey string `json:"document_key,omitempty"`
	// CurrentVersion holds the value of the "current_version" field.
	CurrentVersion int `json:"current_version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RagDocumentQuery when eager-loading is set.
	Edges        RagDocumentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RagDocumentEdges holds the relations/edges for other nodes in the graph.
type RagDocumentEdges struct {
	// Versions holds the value of the versions edge.
	Versions []*RagDocumentVersion `json:"versions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// VersionsOrErr returns the Versions value or an error if the edge
// was not loaded in eager-loading.
func (e RagDocumentEdges) VersionsOrErr() ([]*RagDocumentVersion, error) {
	if e.loadedTypes[0] {
		return e.Versions, nil
	}
	return nil, &NotLoadedError{edge: "versions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RagDocument) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ragdocument.FieldID, ragdocument.FieldCurrentVersion:
			values[i] = new(sql.NullInt64)
		case ragdocument.FieldDocumentKey:
			values[i] = new(sql.NullString)
		case ragdocument.FieldCreatedAt, ragdocument.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RagDocument fields.
func (_m *RagDocument) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ragdocument.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ragdocument.FieldDocumentKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field document_key", values[i])
			} else if value.Valid {
				_m.DocumentKey = value.String
			}
		case ragdocument.FieldCurrentVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_version", values[i])
			} else if value.Valid {
				_m.CurrentVersion = int(value.Int64)
			}
		case ragdocument.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ragdocument.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RagDocument.
// This includes values selected through modifiers, order, etc.
func (_m *RagDocument) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVersions queries the "versions" edge of the RagDocument entity.
func (_m *RagDocument) QueryVersions() *RagDocumentVersionQuery {
	return NewRagDocumentClient(_m.config).QueryVersions(_m)
}

// Update returns a builder for updating this RagDocument.
// Note that you need to call RagDocument.Unwrap() before calling this method if this RagDocument
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RagDocument) Update() *RagDocumentUpdateOne {
	return NewRagDocumentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RagDocument entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RagDocument) Unwrap() *RagDocument {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RagDocument is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RagDocument) String() string {
	var builder strings.Builder
	builder.WriteString("RagDocument(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("document_key=")
	builder.WriteString(_m.DocumentKey)
	builder.WriteString(", ")
	builder.WriteString("current_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentVersion))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RagDocuments is a parsable slice of RagDocument.
type RagDocuments []*RagDocument
