// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PolarishT/sales-agent/ent/ragchunk"
	"github.com/PolarishT/sales-agent/ent/ragdocument"
	"github.com/PolarishT/sales-agent/ent/ragdocumentversion"
	"github.com/google/uuid"
)

// RagDocumentVersionCreate is the builder for creating a RagDocumentVersion entity.
type RagDocumentVersionCreate struct {
	config
	mutation *RagDocumentVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetIngestionID sets the "ingestion_id" field.
func (_c *RagDocumentVersionCreate) SetIngestionID(v uuid.UUID) *RagDocumentVersionCreate {
	_c.mutation.SetIngestionID(v)
	return _c
}

// SetDocumentID sets the "document_id" field.
func (_c *RagDocumentVersionCreate) SetDocumentID(v int64) *RagDocumentVersionCreate {
	_c.mutation.SetDocumentID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *RagDocumentVersionCreate) SetVersion(v int) *RagDocumentVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *RagDocumentVersionCreate) SetFileName(v string) *RagDocumentVersionCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetContentHash sets the "content_hash" field.
func (_c *RagDocumentVersionCreate) SetContentHash(v string) *RagDocumentVersionCreate {
	_c.mutation.SetContentHash(v)
	return _c
}

// SetOriginalMarkdown sets the "original_markdown" field.
func (_c *RagDocumentVersionCreate) SetOriginalMarkdown(v string) *RagDocumentVersionCreate {
	_c.mutation.SetOriginalMarkdown(v)
	return _c
}

// SetSourceBytes sets the "source_bytes" field.
func (_c *RagDocumentVersionCreate) SetSourceBytes(v int64) *RagDocumentVersionCreate {
	_c.mutation.SetSourceBytes(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *RagDocumentVersionCreate) SetStatus(v string) *RagDocumentVersionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetStage sets the "stage" field.
func (_c *RagDocumentVersionCreate) SetStage(v string) *RagDocumentVersionCreate {
	_c.mutation.SetStage(v)
	return _c
}

// SetChunkCount sets the "chunk_count" field.
func (_c *RagDocumentVersionCreate) SetChunkCount(v int) *RagDocumentVersionCreate {
	_c.mutation.SetChunkCount(v)
	return _c
}

// SetNillableChunkCount sets the "chunk_count" field if the given value is not nil.
func (_c *RagDocumentVersionCreate) SetNillableChunkCount(v *int) *RagDocumentVersionCreate {
	if v != nil {
		_c.SetChunkCount(*v)
	}
	return _c
}

// SetEmbeddedChunkCount sets the "embedded_chunk_count" field.
func (_c *RagDocumentVersionCreate) SetEmbeddedChunkCount(v int) *RagDocumentVersionCreate {
	_c.mutation.SetEmbeddedChunkCount(v)
	return _c
}

// SetNillableEmbeddedChunkCount sets the "embedded_chunk_count" field if the given value is not nil.
func (_c *RagDocumentVersionCreate) SetNillableEmbeddedChunkCount(v *int) *RagDocumentVersionCreate {
	if v != nil {
		_c.SetEmbeddedChunkCount(*v)
	}
	return _c
}

// SetFailureCode sets the "failure_code" field.
func (_c *RagDocumentVersionCreate) SetFailureCode(v string) *RagDocumentVersionCreate {
	_c.mutation.SetFailureCode(v)
	return _c
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_c *RagDocumentVersionCreate) SetNillableFailureCode(v *string) *RagDocumentVersionCreate {
	if v != nil {
		_c.SetFailureCode(*v)
	}
	return _c
}

// SetFailureMessage sets the "failure_message" field.
func (_c *RagDocumentVersionCreate) SetFailureMessage(v string) *RagDocumentVersionCreate {
	_c.mutation.SetFailureMessage(v)
	return _c
}

// SetNillableFailureMessage sets the "failure_message" field if the given value is not nil.
func (_c *RagDocumentVersionCreate) SetNillableFailureMessage(v *string) *RagDocumentVersionCreate {
	if v != nil {
		_c.SetFailureMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RagDocumentVersionCreate) SetCreatedAt(v time.Time) *RagDocumentVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RagDocumentVersionCreate) SetNillableCreatedAt(v *time.Time) *RagDocumentVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RagDocumentVersionCreate) SetUpdatedAt(v time.Time) *RagDocumentVersionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RagDocumentVersionCreate) SetNillableUpdatedAt(v *time.Time) *RagDocumentVersionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *RagDocumentVersionCreate) SetCompletedAt(v time.Time) *RagDocumentVersionCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *RagDocumentVersionCreate) SetNillableCompletedAt(v *time.Time) *RagDocumentVersionCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RagDocumentVersionCreate) SetID(v int64) *RagDocumentVersionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetDocument sets the "document" edge to the RagDocument entity.
func (_c *RagDocumentVersionCreate) SetDocument(v *RagDocument) *RagDocumentVersionCreate {
	return _c.SetDocumentID(v.ID)
}

// AddChunkIDs adds the "chunks" edge to the RagChunk entity by IDs.
func (_c *RagDocumentVersionCreate) AddChunkIDs(ids ...int64) *RagDocumentVersionCreate {
	_c.mutation.AddChunkIDs(ids...)
	return _c
}

// AddChunks adds the "chunks" edges to the RagChunk entity.
func (_c *RagDocumentVersionCreate) AddChunks(v ...*RagChunk) *RagDocumentVersionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChunkIDs(ids...)
}

// Mutation returns the RagDocumentVersionMutation object of the builder.
func (_c *RagDocumentVersionCreate) Mutation() *RagDocumentVersionMutation {
	return _c.mutation
}

// Save creates the RagDocumentVersion in the database.
func (_c *RagDocumentVersionCreate) Save(ctx context.Context) (*RagDocumentVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RagDocumentVersionCreate) SaveX(ctx context.Context) *RagDocumentVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RagDocumentVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RagDocumentVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RagDocumentVersionCreate) defaults() {
	if _, ok := _c.mutation.ChunkCount(); !ok {
		v := ragdocumentversion.DefaultChunkCount
		_c.mutation.SetChunkCount(v)
	}
	if _, ok := _c.mutation.EmbeddedChunkCount(); !ok {
		v := ragdocumentversion.DefaultEmbeddedChunkCount
		_c.mutation.SetEmbeddedChunkCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ragdocumentversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ragdocumentversion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RagDocumentVersionCreate) check() error {
	if _, ok := _c.mutation.IngestionID(); !ok {
		return &ValidationError{Name: "ingestion_id", err: errors.New(`ent: missing required field "RagDocumentVersion.ingestion_id"`)}
	}
	if _, ok := _c.mutation.DocumentID(); !ok {
		return &ValidationError{Name: "document_id", err: errors.New(`ent: missing required field "RagDocumentVersion.document_id"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "RagDocumentVersion.version"`)}
	}
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "RagDocumentVersion.file_name"`)}
	}
	if v, ok := _c.mutation.FileName(); ok {
		if err := ragdocumentversion.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "RagDocumentVersion.file_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentHash(); !ok {
		return &ValidationError{Name: "content_hash", err: errors.New(`ent: missing required field "RagDocumentVersion.content_hash"`)}
	}
	if _, ok := _c.mutation.OriginalMarkdown(); !ok {
		return &ValidationError{Name: "original_markdown", err: errors.New(`ent: missing required field "RagDocumentVersion.original_markdown"`)}
	}
	if _, ok := _c.mutation.SourceBytes(); !ok {
		return &ValidationError{Name: "source_bytes", err: errors.New(`ent: missing required field "RagDocumentVersion.source_bytes"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RagDocumentVersion.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := ragdocumentversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RagDocumentVersion.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Stage(); !ok {
		return &ValidationError{Name: "stage", err: errors.New(`ent: missing required field "RagDocumentVersion.stage"`)}
	}
	if v, ok := _c.mutation.Stage(); ok {
		if err := ragdocumentversion.StageValidator(v); err != nil {
			return &ValidationError{Name: "stage", err: fmt.Errorf(`ent: validator failed for field "RagDocumentVersion.stage": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChunkCount(); !ok {
		return &ValidationError{Name: "chunk_count", err: errors.New(`ent: missing required field "RagDocumentVersion.chunk_count"`)}
	}
	if _, ok := _c.mutation.EmbeddedChunkCount(); !ok {
		return &ValidationError{Name: "embedded_chunk_count", err: errors.New(`ent: missing required field "RagDocumentVersion.embedded_chunk_count"`)}
	}
	if v, ok := _c.mutation.FailureCode(); ok {
		if err := ragdocumentversion.FailureCodeValidator(v); err != nil {
			return &ValidationError{Name: "failure_code", err: fmt.Errorf(`ent: validator failed for field "RagDocumentVersion.failure_code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.FailureMessage(); ok {
		if err := ragdocumentversion.FailureMessageValidator(v); err != nil {
			return &ValidationError{Name: "failure_message", err: fmt.Errorf(`ent: validator failed for field "RagDocumentVersion.failure_message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RagDocumentVersion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RagDocumentVersion.updated_at"`)}
	}
	if len(_c.mutation.DocumentIDs()) == 0 {
		return &ValidationError{Name: "document", err: errors.New(`ent: missing required edge "RagDocumentVersion.document"`)}
	}
	return nil
}

func (_c *RagDocumentVersionCreate) sqlSave(ctx context.Context) (*RagDocumentVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RagDocumentVersionCreate) createSpec() (*RagDocumentVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &RagDocumentVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ragdocumentversion.Table, sqlgraph.NewFieldSpec(ragdocumentversion.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.IngestionID(); ok {
		_spec.SetField(ragdocumentversion.FieldIngestionID, field.TypeUUID, value)
		_node.IngestionID = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(ragdocumentversion.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(ragdocumentversion.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.ContentHash(); ok {
		_spec.SetField(ragdocumentversion.FieldContentHash, field.TypeString, value)
		_node.ContentHash = value
	}
	if value, ok := _c.mutation.OriginalMarkdown(); ok {
		_spec.SetField(ragdocumentversion.FieldOriginalMarkdown, field.TypeString, value)
		_node.OriginalMarkdown = value
	}
	if value, ok := _c.mutation.SourceBytes(); ok {
		_spec.SetField(ragdocumentversion.FieldSourceBytes, field.TypeInt64, value)
		_node.SourceBytes = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ragdocumentversion.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Stage(); ok {
		_spec.SetField(ragdocumentversion.FieldStage, field.TypeString, value)
		_node.Stage = value
	}
	if value, ok := _c.mutation.ChunkCount(); ok {
		_spec.SetField(ragdocumentversion.FieldChunkCount, field.TypeInt, value)
		_node.ChunkCount = value
	}
	if value, ok := _c.mutation.EmbeddedChunkCount(); ok {
		_spec.SetField(ragdocumentversion.FieldEmbeddedChunkCount, field.TypeInt, value)
		_node.EmbeddedChunkCount = value
	}
	if value, ok := _c.mutation.FailureCode(); ok {
		_spec.SetField(ragdocumentversion.FieldFailureCode, field.TypeString, value)
		_node.FailureCode = &value
	}
	if value, ok := _c.mutation.FailureMessage(); ok {
		_spec.SetField(ragdocumentversion.FieldFailureMessage, field.TypeString, value)
		_node.FailureMessage = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ragdocumentversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ragdocumentversion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(ragdocumentversion.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if nodes := _c.mutation.DocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ragdocumentversion.DocumentTable,
			Columns: []string{ragdocumentversion.DocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ragdocument.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DocumentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChunksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ragdocumentversion.ChunksTable,
			Columns: []string{ragdocumentversion.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ragchunk.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RagDocumentVersion.Create().
//		SetIngestionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RagDocumentVersionUpsert) {
//			SetIngestionID(v+v).
//		}).
//		Exec(ctx)
func (_c *RagDocumentVersionCreate) OnConflict(opts ...sql.ConflictOption) *RagDocumentVersionUpsertOne {
	_c.conflict = opts
	return &RagDocumentVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RagDocumentVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RagDocumentVersionCreate) OnConflictColumns(columns ...string) *RagDocumentVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RagDocumentVersionUpsertOne{
		create: _c,
	}
}

type (
	// RagDocumentVersionUpsertOne is the builder for "upsert"-ing
	//  one RagDocumentVersion node.
	RagDocumentVersionUpsertOne struct {
		create *RagDocumentVersionCreate
	}

	// RagDocumentVersionUpsert is the "OnConflict" setter.
	RagDocumentVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetIngestionID sets the "ingestion_id" field.
func (u *RagDocumentVersionUpsert) SetIngestionID(v uuid.UUID) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldIngestionID, v)
	return u
}

// UpdateIngestionID sets the "ingestion_id" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateIngestionID() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldIngestionID)
	return u
}

// SetDocumentID sets the "document_id" field.
func (u *RagDocumentVersionUpsert) SetDocumentID(v int64) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldDocumentID, v)
	return u
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateDocumentID() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldDocumentID)
	return u
}

// SetVersion sets the "version" field.
func (u *RagDocumentVersionUpsert) SetVersion(v int) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateVersion() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *RagDocumentVersionUpsert) AddVersion(v int) *RagDocumentVersionUpsert {
	u.Add(ragdocumentversion.FieldVersion, v)
	return u
}

// SetFileName sets the "file_name" field.
func (u *RagDocumentVersionUpsert) SetFileName(v string) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldFileName, v)
	return u
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateFileName() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldFileName)
	return u
}

// SetContentHash sets the "content_hash" field.
func (u *RagDocumentVersionUpsert) SetContentHash(v string) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldContentHash, v)
	return u
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateContentHash() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldContentHash)
	return u
}

// SetOriginalMarkdown sets the "original_markdown" field.
func (u *RagDocumentVersionUpsert) SetOriginalMarkdown(v string) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldOriginalMarkdown, v)
	return u
}

// UpdateOriginalMarkdown sets the "original_markdown" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateOriginalMarkdown() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldOriginalMarkdown)
	return u
}

// SetSourceBytes sets the "source_bytes" field.
func (u *RagDocumentVersionUpsert) SetSourceBytes(v int64) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldSourceBytes, v)
	return u
}

// UpdateSourceBytes sets the "source_bytes" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateSourceBytes() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldSourceBytes)
	return u
}

// AddSourceBytes adds v to the "source_bytes" field.
func (u *RagDocumentVersionUpsert) AddSourceBytes(v int64) *RagDocumentVersionUpsert {
	u.Add(ragdocumentversion.FieldSourceBytes, v)
	return u
}

// SetStatus sets the "status" field.
func (u *RagDocumentVersionUpsert) SetStatus(v string) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateStatus() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldStatus)
	return u
}

// SetStage sets the "stage" field.
func (u *RagDocumentVersionUpsert) SetStage(v string) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldStage, v)
	return u
}

// UpdateStage sets the "stage" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateStage() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldStage)
	return u
}

// SetChunkCount sets the "chunk_count" field.
func (u *RagDocumentVersionUpsert) SetChunkCount(v int) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldChunkCount, v)
	return u
}

// UpdateChunkCount sets the "chunk_count" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateChunkCount() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldChunkCount)
	return u
}

// AddChunkCount adds v to the "chunk_count" field.
func (u *RagDocumentVersionUpsert) AddChunkCount(v int) *RagDocumentVersionUpsert {
	u.Add(ragdocumentversion.FieldChunkCount, v)
	return u
}

// SetEmbeddedChunkCount sets the "embedded_chunk_count" field.
func (u *RagDocumentVersionUpsert) SetEmbeddedChunkCount(v int) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldEmbeddedChunkCount, v)
	return u
}

// UpdateEmbeddedChunkCount sets the "embedded_chunk_count" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateEmbeddedChunkCount() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldEmbeddedChunkCount)
	return u
}

// AddEmbeddedChunkCount adds v to the "embedded_chunk_count" field.
func (u *RagDocumentVersionUpsert) AddEmbeddedChunkCount(v int) *RagDocumentVersionUpsert {
	u.Add(ragdocumentversion.FieldEmbeddedChunkCount, v)
	return u
}

// SetFailureCode sets the "failure_code" field.
func (u *RagDocumentVersionUpsert) SetFailureCode(v string) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldFailureCode, v)
	return u
}

// UpdateFailureCode sets the "failure_code" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateFailureCode() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldFailureCode)
	return u
}

// ClearFailureCode clears the value of the "failure_code" field.
func (u *RagDocumentVersionUpsert) ClearFailureCode() *RagDocumentVersionUpsert {
	u.SetNull(ragdocumentversion.FieldFailureCode)
	return u
}

// SetFailureMessage sets the "failure_message" field.
func (u *RagDocumentVersionUpsert) SetFailureMessage(v string) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldFailureMessage, v)
	return u
}

// UpdateFailureMessage sets the "failure_message" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateFailureMessage() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldFailureMessage)
	return u
}

// ClearFailureMessage clears the value of the "failure_message" field.
func (u *RagDocumentVersionUpsert) ClearFailureMessage() *RagDocumentVersionUpsert {
	u.SetNull(ragdocumentversion.FieldFailureMessage)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RagDocumentVersionUpsert) SetUpdatedAt(v time.Time) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateUpdatedAt() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldUpdatedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *RagDocumentVersionUpsert) SetCompletedAt(v time.Time) *RagDocumentVersionUpsert {
	u.Set(ragdocumentversion.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *RagDocumentVersionUpsert) UpdateCompletedAt() *RagDocumentVersionUpsert {
	u.SetExcluded(ragdocumentversion.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *RagDocumentVersionUpsert) ClearCompletedAt() *RagDocumentVersionUpsert {
	u.SetNull(ragdocumentversion.FieldCompletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RagDocumentVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ragdocumentversion.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RagDocumentVersionUpsertOne) UpdateNewValues() *RagDocumentVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ragdocumentversion.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ragdocumentversion.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RagDocumentVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RagDocumentVersionUpsertOne) Ignore() *RagDocumentVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RagDocumentVersionUpsertOne) DoNothing() *RagDocumentVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RagDocumentVersionCreate.OnConflict
// documentation for more info.
func (u *RagDocumentVersionUpsertOne) Update(set func(*RagDocumentVersionUpsert)) *RagDocumentVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RagDocumentVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetIngestionID sets the "ingestion_id" field.
func (u *RagDocumentVersionUpsertOne) SetIngestionID(v uuid.UUID) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetIngestionID(v)
	})
}

// UpdateIngestionID sets the "ingestion_id" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateIngestionID() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateIngestionID()
	})
}

// SetDocumentID sets the "document_id" field.
func (u *RagDocumentVersionUpsertOne) SetDocumentID(v int64) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetDocumentID(v)
	})
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateDocumentID() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateDocumentID()
	})
}

// SetVersion sets the "version" field.
func (u *RagDocumentVersionUpsertOne) SetVersion(v int) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *RagDocumentVersionUpsertOne) AddVersion(v int) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateVersion() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateVersion()
	})
}

// SetFileName sets the "file_name" field.
func (u *RagDocumentVersionUpsertOne) SetFileName(v string) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateFileName() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateFileName()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *RagDocumentVersionUpsertOne) SetContentHash(v string) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateContentHash() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateContentHash()
	})
}

// SetOriginalMarkdown sets the "original_markdown" field.
func (u *RagDocumentVersionUpsertOne) SetOriginalMarkdown(v string) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetOriginalMarkdown(v)
	})
}

// UpdateOriginalMarkdown sets the "original_markdown" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateOriginalMarkdown() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateOriginalMarkdown()
	})
}

// SetSourceBytes sets the "source_bytes" field.
func (u *RagDocumentVersionUpsertOne) SetSourceBytes(v int64) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetSourceBytes(v)
	})
}

// AddSourceBytes adds v to the "source_bytes" field.
func (u *RagDocumentVersionUpsertOne) AddSourceBytes(v int64) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.AddSourceBytes(v)
	})
}

// UpdateSourceBytes sets the "source_bytes" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateSourceBytes() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateSourceBytes()
	})
}

// SetStatus sets the "status" field.
func (u *RagDocumentVersionUpsertOne) SetStatus(v string) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateStatus() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateStatus()
	})
}

// SetStage sets the "stage" field.
func (u *RagDocumentVersionUpsertOne) SetStage(v string) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetStage(v)
	})
}

// UpdateStage sets the "stage" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateStage() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateStage()
	})
}

// SetChunkCount sets the "chunk_count" field.
func (u *RagDocumentVersionUpsertOne) SetChunkCount(v int) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetChunkCount(v)
	})
}

// AddChunkCount adds v to the "chunk_count" field.
func (u *RagDocumentVersionUpsertOne) AddChunkCount(v int) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.AddChunkCount(v)
	})
}

// UpdateChunkCount sets the "chunk_count" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateChunkCount() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateChunkCount()
	})
}

// SetEmbeddedChunkCount sets the "embedded_chunk_count" field.
func (u *RagDocumentVersionUpsertOne) SetEmbeddedChunkCount(v int) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetEmbeddedChunkCount(v)
	})
}

// AddEmbeddedChunkCount adds v to the "embedded_chunk_count" field.
func (u *RagDocumentVersionUpsertOne) AddEmbeddedChunkCount(v int) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.AddEmbeddedChunkCount(v)
	})
}

// UpdateEmbeddedChunkCount sets the "embedded_chunk_count" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateEmbeddedChunkCount() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateEmbeddedChunkCount()
	})
}

// SetFailureCode sets the "failure_code" field.
func (u *RagDocumentVersionUpsertOne) SetFailureCode(v string) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetFailureCode(v)
	})
}

// UpdateFailureCode sets the "failure_code" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateFailureCode() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateFailureCode()
	})
}

// ClearFailureCode clears the value of the "failure_code" field.
func (u *RagDocumentVersionUpsertOne) ClearFailureCode() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.ClearFailureCode()
	})
}

// SetFailureMessage sets the "failure_message" field.
func (u *RagDocumentVersionUpsertOne) SetFailureMessage(v string) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetFailureMessage(v)
	})
}

// UpdateFailureMessage sets the "failure_message" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateFailureMessage() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateFailureMessage()
	})
}

// ClearFailureMessage clears the value of the "failure_message" field.
func (u *RagDocumentVersionUpsertOne) ClearFailureMessage() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.ClearFailureMessage()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RagDocumentVersionUpsertOne) SetUpdatedAt(v time.Time) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateUpdatedAt() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *RagDocumentVersionUpsertOne) SetCompletedAt(v time.Time) *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertOne) UpdateCompletedAt() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *RagDocumentVersionUpsertOne) ClearCompletedAt() *RagDocumentVersionUpsertOne {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *RagDocumentVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RagDocumentVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RagDocumentVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RagDocumentVersionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RagDocumentVersionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RagDocumentVersionCreateBulk is the builder for creating many RagDocumentVersion entities in bulk.
type RagDocumentVersionCreateBulk struct {
	config
	err      error
	builders []*RagDocumentVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the RagDocumentVersion entities in the database.
func (_c *RagDocumentVersionCreateBulk) Save(ctx context.Context) ([]*RagDocumentVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RagDocumentVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RagDocumentVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RagDocumentVersionCreateBulk) SaveX(ctx context.Context) []*RagDocumentVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RagDocumentVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RagDocumentVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RagDocumentVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RagDocumentVersionUpsert) {
//			SetIngestionID(v+v).
//		}).
//		Exec(ctx)
func (_c *RagDocumentVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *RagDocumentVersionUpsertBulk {
	_c.conflict = opts
	return &RagDocumentVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RagDocumentVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RagDocumentVersionCreateBulk) OnConflictColumns(columns ...string) *RagDocumentVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RagDocumentVersionUpsertBulk{
		create: _c,
	}
}

// RagDocumentVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of RagDocumentVersion nodes.
type RagDocumentVersionUpsertBulk struct {
	create *RagDocumentVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RagDocumentVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ragdocumentversion.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RagDocumentVersionUpsertBulk) UpdateNewValues() *RagDocumentVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ragdocumentversion.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ragdocumentversion.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RagDocumentVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RagDocumentVersionUpsertBulk) Ignore() *RagDocumentVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RagDocumentVersionUpsertBulk) DoNothing() *RagDocumentVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RagDocumentVersionCreateBulk.OnConflict
// documentation for more info.
func (u *RagDocumentVersionUpsertBulk) Update(set func(*RagDocumentVersionUpsert)) *RagDocumentVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RagDocumentVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetIngestionID sets the "ingestion_id" field.
func (u *RagDocumentVersionUpsertBulk) SetIngestionID(v uuid.UUID) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetIngestionID(v)
	})
}

// UpdateIngestionID sets the "ingestion_id" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateIngestionID() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateIngestionID()
	})
}

// SetDocumentID sets the "document_id" field.
func (u *RagDocumentVersionUpsertBulk) SetDocumentID(v int64) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetDocumentID(v)
	})
}

// UpdateDocumentID sets the "document_id" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateDocumentID() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateDocumentID()
	})
}

// SetVersion sets the "version" field.
func (u *RagDocumentVersionUpsertBulk) SetVersion(v int) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *RagDocumentVersionUpsertBulk) AddVersion(v int) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateVersion() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateVersion()
	})
}

// SetFileName sets the "file_name" field.
func (u *RagDocumentVersionUpsertBulk) SetFileName(v string) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetFileName(v)
	})
}

// UpdateFileName sets the "file_name" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateFileName() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateFileName()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *RagDocumentVersionUpsertBulk) SetContentHash(v string) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateContentHash() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateContentHash()
	})
}

// SetOriginalMarkdown sets the "original_markdown" field.
func (u *RagDocumentVersionUpsertBulk) SetOriginalMarkdown(v string) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetOriginalMarkdown(v)
	})
}

// UpdateOriginalMarkdown sets the "original_markdown" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateOriginalMarkdown() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateOriginalMarkdown()
	})
}

// SetSourceBytes sets the "source_bytes" field.
func (u *RagDocumentVersionUpsertBulk) SetSourceBytes(v int64) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetSourceBytes(v)
	})
}

// AddSourceBytes adds v to the "source_bytes" field.
func (u *RagDocumentVersionUpsertBulk) AddSourceBytes(v int64) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.AddSourceBytes(v)
	})
}

// UpdateSourceBytes sets the "source_bytes" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateSourceBytes() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateSourceBytes()
	})
}

// SetStatus sets the "status" field.
func (u *RagDocumentVersionUpsertBulk) SetStatus(v string) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateStatus() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateStatus()
	})
}

// SetStage sets the "stage" field.
func (u *RagDocumentVersionUpsertBulk) SetStage(v string) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetStage(v)
	})
}

// UpdateStage sets the "stage" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateStage() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateStage()
	})
}

// SetChunkCount sets the "chunk_count" field.
func (u *RagDocumentVersionUpsertBulk) SetChunkCount(v int) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetChunkCount(v)
	})
}

// AddChunkCount adds v to the "chunk_count" field.
func (u *RagDocumentVersionUpsertBulk) AddChunkCount(v int) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.AddChunkCount(v)
	})
}

// UpdateChunkCount sets the "chunk_count" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateChunkCount() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateChunkCount()
	})
}

// SetEmbeddedChunkCount sets the "embedded_chunk_count" field.
func (u *RagDocumentVersionUpsertBulk) SetEmbeddedChunkCount(v int) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetEmbeddedChunkCount(v)
	})
}

// AddEmbeddedChunkCount adds v to the "embedded_chunk_count" field.
func (u *RagDocumentVersionUpsertBulk) AddEmbeddedChunkCount(v int) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.AddEmbeddedChunkCount(v)
	})
}

// UpdateEmbeddedChunkCount sets the "embedded_chunk_count" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateEmbeddedChunkCount() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateEmbeddedChunkCount()
	})
}

// SetFailureCode sets the "failure_code" field.
func (u *RagDocumentVersionUpsertBulk) SetFailureCode(v string) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetFailureCode(v)
	})
}

// UpdateFailureCode sets the "failure_code" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateFailureCode() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateFailureCode()
	})
}

// ClearFailureCode clears the value of the "failure_code" field.
func (u *RagDocumentVersionUpsertBulk) ClearFailureCode() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.ClearFailureCode()
	})
}

// SetFailureMessage sets the "failure_message" field.
func (u *RagDocumentVersionUpsertBulk) SetFailureMessage(v string) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetFailureMessage(v)
	})
}

// UpdateFailureMessage sets the "failure_message" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateFailureMessage() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateFailureMessage()
	})
}

// ClearFailureMessage clears the value of the "failure_message" field.
func (u *RagDocumentVersionUpsertBulk) ClearFailureMessage() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.ClearFailureMessage()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RagDocumentVersionUpsertBulk) SetUpdatedAt(v time.Time) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateUpdatedAt() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *RagDocumentVersionUpsertBulk) SetCompletedAt(v time.Time) *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *RagDocumentVersionUpsertBulk) UpdateCompletedAt() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *RagDocumentVersionUpsertBulk) ClearCompletedAt() *RagDocumentVersionUpsertBulk {
	return u.Update(func(s *RagDocumentVersionUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *RagDocumentVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RagDocumentVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RagDocumentVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RagDocumentVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
