// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PolarishT/sales-agent/ent/raguser"
)

// RagUserCreate is the builder for creating a RagUser entity.
type RagUserCreate struct {
	config
	mutation *RagUserMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *RagUserCreate) SetUserID(v string) *RagUserCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *RagUserCreate) SetMetadata(v map[string]interface{}) *RagUserCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_c *RagUserCreate) SetFirstSeenAt(v time.Time) *RagUserCreate {
	_c.mutation.SetFirstSeenAt(v)
	return _c
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_c *RagUserCreate) SetNillableFirstSeenAt(v *time.Time) *RagUserCreate {
	if v != nil {
		_c.SetFirstSeenAt(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *RagUserCreate) SetLastSeenAt(v time.Time) *RagUserCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *RagUserCreate) SetNillableLastSeenAt(v *time.Time) *RagUserCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RagUserCreate) SetID(v int64) *RagUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RagUserMutation object of the builder.
func (_c *RagUserCreate) Mutation() *RagUserMutation {
	return _c.mutation
}

// Save creates the RagUser in the database.
func (_c *RagUserCreate) Save(ctx context.Context) (*RagUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RagUserCreate) SaveX(ctx context.Context) *RagUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RagUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RagUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RagUserCreate) defaults() {
	if _, ok := _c.mutation.Metadata(); !ok {
		v := raguser.DefaultMetadata()
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.FirstSeenAt(); !ok {
		v := raguser.DefaultFirstSeenAt()
		_c.mutation.SetFirstSeenAt(v)
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		v := raguser.DefaultLastSeenAt()
		_c.mutation.SetLastSeenAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RagUserCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RagUser.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := raguser.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "RagUser.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "RagUser.metadata"`)}
	}
	if _, ok := _c.mutation.FirstSeenAt(); !ok {
		return &ValidationError{Name: "first_seen_at", err: errors.New(`ent: missing required field "RagUser.first_seen_at"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "RagUser.last_seen_at"`)}
	}
	return nil
}

func (_c *RagUserCreate) sqlSave(ctx context.Context) (*RagUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RagUserCreate) createSpec() (*RagUser, *sqlgraph.CreateSpec) {
	var (
		_node = &RagUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(raguser.Table, sqlgraph.NewFieldSpec(raguser.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(raguser.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(raguser.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.FirstSeenAt(); ok {
		_spec.SetField(raguser.FieldFirstSeenAt, field.TypeTime, value)
		_node.FirstSeenAt = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(raguser.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	return _node, _spec
}

// RagUserCreateBulk is the builder for creating many RagUser entities in bulk.
type RagUserCreateBulk struct {
	config
	err      error
	builders []*RagUserCreate
}

// Save creates the RagUser entities in the database.
func (_c *RagUserCreateBulk) Save(ctx context.Context) ([]*RagUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RagUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RagUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RagUserCreateBulk) SaveX(ctx context.Context) []*RagUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RagUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RagUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
