// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/PolarishT/sales-agent/ent/predicate"
	"github.com/PolarishT/sales-agent/ent/raguser"
)

// RagUserUpdate is the builder for updating RagUser entities.
type RagUserUpdate struct {
	config
	hooks    []Hook
	mutation *RagUserMutation
}

// Where appends a list predicates to the RagUserUpdate builder.
func (_u *RagUserUpdate) Where(ps ...predicate.RagUser) *RagUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RagUserUpdate) SetUserID(v string) *RagUserUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RagUserUpdate) SetNillableUserID(v *string) *RagUserUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RagUserUpdate) SetMetadata(v map[string]interface{}) *RagUserUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_u *RagUserUpdate) SetFirstSeenAt(v time.Time) *RagUserUpdate {
	_u.mutation.SetFirstSeenAt(v)
	return _u
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_u *RagUserUpdate) SetNillableFirstSeenAt(v *time.Time) *RagUserUpdate {
	if v != nil {
		_u.SetFirstSeenAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *RagUserUpdate) SetLastSeenAt(v time.Time) *RagUserUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *RagUserUpdate) SetNillableLastSeenAt(v *time.Time) *RagUserUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// Mutation returns the RagUserMutation object of the builder.
func (_u *RagUserUpdate) Mutation() *RagUserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RagUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RagUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RagUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RagUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RagUserUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := raguser.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "RagUser.user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *RagUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(raguser.Table, raguser.Columns, sqlgraph.NewFieldSpec(raguser.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(raguser.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(raguser.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.FirstSeenAt(); ok {
		_spec.SetField(raguser.FieldFirstSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(raguser.FieldLastSeenAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{raguser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RagUserUpdateOne is the builder for updating a single RagUser entity.
type RagUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RagUserMutation
}

// SetUserID sets the "user_id" field.
func (_u *RagUserUpdateOne) SetUserID(v string) *RagUserUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RagUserUpdateOne) SetNillableUserID(v *string) *RagUserUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *RagUserUpdateOne) SetMetadata(v map[string]interface{}) *RagUserUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_u *RagUserUpdateOne) SetFirstSeenAt(v time.Time) *RagUserUpdateOne {
	_u.mutation.SetFirstSeenAt(v)
	return _u
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_u *RagUserUpdateOne) SetNillableFirstSeenAt(v *time.Time) *RagUserUpdateOne {
	if v != nil {
		_u.SetFirstSeenAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *RagUserUpdateOne) SetLastSeenAt(v time.Time) *RagUserUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *RagUserUpdateOne) SetNillableLastSeenAt(v *time.Time) *RagUserUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// Mutation returns the RagUserMutation object of the builder.
func (_u *RagUserUpdateOne) Mutation() *RagUserMutation {
	return _u.mutation
}

// Where appends a list predicates to the RagUserUpdate builder.
func (_u *RagUserUpdateOne) Where(ps ...predicate.RagUser) *RagUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RagUserUpdateOne) Select(field string, fields ...string) *RagUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RagUser entity.
func (_u *RagUserUpdateOne) Save(ctx context.Context) (*RagUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RagUserUpdateOne) SaveX(ctx context.Context) *RagUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RagUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RagUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RagUserUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := raguser.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "RagUser.user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *RagUserUpdateOne) sqlSave(ctx context.Context) (_node *RagUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(raguser.Table, raguser.Columns, sqlgraph.NewFieldSpec(raguser.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RagUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, raguser.FieldID)
		for _, f := range fields {
			if !raguser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != raguser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(raguser.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(raguser.FieldMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.FirstSeenAt(); ok {
		_spec.SetField(raguser.FieldFirstSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(raguser.FieldLastSeenAt, field.TypeTime, value)
	}
	_node = &RagUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{raguser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
