// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/PolarishT/sales-agent/ent/raguser"
	"github.com/PolarishT/sales-agent/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	raguserFields := schema.RagUser{}.Fields()
	_ = raguserFields
	// raguserDescUserID is the schema descriptor for user_id field.
	raguserDescUserID := raguserFields[1].Descriptor()
	// raguser.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	raguser.UserIDValidator = raguserDescUserID.Validators[0].(func(string) error)
	// raguserDescMetadata is the schema descriptor for metadata field.
	raguserDescMetadata := raguserFields[2].Descriptor()
	// raguser.DefaultMetadata holds the default value on creation for the metadata field.
	raguser.DefaultMetadata = raguserDescMetadata.Default.(func() map[string]interface{})
	// raguserDescFirstSeenAt is the schema descriptor for first_seen_at field.
	raguserDescFirstSeenAt := raguserFields[3].Descriptor()
	// raguser.DefaultFirstSeenAt holds the default value on creation for the first_seen_at field.
	raguser.DefaultFirstSeenAt = raguserDescFirstSeenAt.Default.(func() time.Time)
	// raguserDescLastSeenAt is the schema descriptor for last_seen_at field.
	raguserDescLastSeenAt := raguserFields[4].Descriptor()
	// raguser.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	raguser.DefaultLastSeenAt = raguserDescLastSeenAt.Default.(func() time.Time)
}
