// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	health "github.com/PolarishT/sales-agent/biz/router/health"
	rag_ingestion "github.com/PolarishT/sales-agent/biz/router/rag_ingestion"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	rag_ingestion.Register(r)

	health.Register(r)
}
