// Code generated by ent, DO NOT EDIT.

package ragdocument

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ragdocument type in the database.
	Label = "rag_document"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDocumentKey holds the string denoting the document_key field in the database.
	FieldDocumentKey = "document_key"
	// FieldCurrentVersion holds the string denoting the current_version field in the database.
	FieldCurrentVersion = "current_version"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeVersions holds the string denoting the versions edge name in mutations.
	EdgeVersions = "versions"
	// Table holds the table name of the ragdocument in the database.
	Table = "rag_documents"
	// VersionsTable is the table that holds the versions relation/edge.
	VersionsTable = "rag_document_versions"
	// VersionsInverseTable is the table name for the RagDocumentVersion entity.
	// It exists in this package in order to avoid circular dependency with the "ragdocumentversion" package.
	VersionsInverseTable = "rag_document_versions"
	// VersionsColumn is the table column denoting the versions relation/edge.
	VersionsColumn = "document_id"
)

// Columns holds all SQL columns for ragdocument fields.
var Columns = []string{
	FieldID,
	FieldDocumentKey,
	FieldCurrentVersion,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DocumentKeyValidator is a validator for the "document_key" field. It is called by the builders before save.
	DocumentKeyValidator func(string) error
	// DefaultCurrentVersion holds the default value on creation for the "current_version" field.
	DefaultCurrentVersion int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the RagDocument queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDocumentKey orders the results by the document_key field.
func ByDocumentKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocumentKey, opts...).ToFunc()
}

// ByCurrentVersion orders the results by the current_version field.
func ByCurrentVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByVersionsCount orders the results by versions count.
func ByVersionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVersionsStep(), opts...)
	}
}

// ByVersions orders the results by versions terms.
func ByVersions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVersionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newVersionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VersionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VersionsTable, VersionsColumn),
	)
}
