// Code generated by ent, DO NOT EDIT.

package ragdocument

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/PolarishT/sales-agent/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldLTE(FieldID, id))
}

// DocumentKey applies equality check predicate on the "document_key" field. It's identical to DocumentKeyEQ.
func DocumentKey(v string) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldEQ(FieldDocumentKey, v))
}

// CurrentVersion applies equality check predicate on the "current_version" field. It's identical to CurrentVersionEQ.
func CurrentVersion(v int) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldEQ(FieldCurrentVersion, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldEQ(FieldUpdatedAt, v))
}

// DocumentKeyEQ applies the EQ predicate on the "document_key" field.
func DocumentKeyEQ(v string) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldEQ(FieldDocumentKey, v))
}

// DocumentKeyNEQ applies the NEQ predicate on the "document_key" field.
func DocumentKeyNEQ(v string) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldNEQ(FieldDocumentKey, v))
}

// DocumentKeyIn applies the In predicate on the "document_key" field.
func DocumentKeyIn(vs ...string) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldIn(FieldDocumentKey, vs...))
}

// DocumentKeyNotIn applies the NotIn predicate on the "document_key" field.
func DocumentKeyNotIn(vs ...string) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldNotIn(FieldDocumentKey, vs...))
}

// DocumentKeyGT applies the GT predicate on the "document_key" field.
func DocumentKeyGT(v string) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldGT(FieldDocumentKey, v))
}

// DocumentKeyGTE applies the GTE predicate on the "document_key" field.
func DocumentKeyGTE(v string) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldGTE(FieldDocumentKey, v))
}

// DocumentKeyLT applies the LT predicate on the "document_key" field.
func DocumentKeyLT(v string) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldLT(FieldDocumentKey, v))
}

// DocumentKeyLTE applies the LTE predicate on the "document_key" field.
func DocumentKeyLTE(v string) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldLTE(FieldDocumentKey, v))
}

// DocumentKeyContains applies the Contains predicate on the "document_key" field.
func DocumentKeyContains(v string) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldContains(FieldDocumentKey, v))
}

// DocumentKeyHasPrefix applies the HasPrefix predicate on the "document_key" field.
func DocumentKeyHasPrefix(v string) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldHasPrefix(FieldDocumentKey, v))
}

// DocumentKeyHasSuffix applies the HasSuffix predicate on the "document_key" field.
func DocumentKeyHasSuffix(v string) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldHasSuffix(FieldDocumentKey, v))
}

// DocumentKeyEqualFold applies the EqualFold predicate on the "document_key" field.
func DocumentKeyEqualFold(v string) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldEqualFold(FieldDocumentKey, v))
}

// DocumentKeyContainsFold applies the ContainsFold predicate on the "document_key" field.
func DocumentKeyContainsFold(v string) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldContainsFold(FieldDocumentKey, v))
}

// CurrentVersionEQ applies the EQ predicate on the "current_version" field.
func CurrentVersionEQ(v int) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldEQ(FieldCurrentVersion, v))
}

// CurrentVersionNEQ applies the NEQ predicate on the "current_version" field.
func CurrentVersionNEQ(v int) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldNEQ(FieldCurrentVersion, v))
}

// CurrentVersionIn applies the In predicate on the "current_version" field.
func CurrentVersionIn(vs ...int) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldIn(FieldCurrentVersion, vs...))
}

// CurrentVersionNotIn applies the NotIn predicate on the "current_version" field.
func CurrentVersionNotIn(vs ...int) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldNotIn(FieldCurrentVersion, vs...))
}

// CurrentVersionGT applies the GT predicate on the "current_version" field.
func CurrentVersionGT(v int) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldGT(FieldCurrentVersion, v))
}

// CurrentVersionGTE applies the GTE predicate on the "current_version" field.
func CurrentVersionGTE(v int) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldGTE(FieldCurrentVersion, v))
}

// CurrentVersionLT applies the LT predicate on the "current_version" field.
func CurrentVersionLT(v int) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldLT(FieldCurrentVersion, v))
}

// CurrentVersionLTE applies the LTE predicate on the "current_version" field.
func CurrentVersionLTE(v int) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldLTE(FieldCurrentVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RagDocument {
	return predicate.RagDocument(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasVersions applies the HasEdge predicate on the "versions" edge.
func HasVersions() predicate.RagDocument {
	return predicate.RagDocument(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VersionsTable, VersionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVersionsWith applies the HasEdge predicate on the "versions" edge with a given conditions (other predicates).
func HasVersionsWith(preds ...predicate.RagDocumentVersion) predicate.RagDocument {
	return predicate.RagDocument(func(s *sql.Selector) {
		step := newVersionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RagDocument) predicate.RagDocument {
	return predicate.RagDocument(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RagDocument) predicate.RagDocument {
	return predicate.RagDocument(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RagDocument) predicate.RagDocument {
	return predicate.RagDocument(sql.NotPredicates(p))
}
