// Code generated by ent, DO NOT EDIT.

package raguser

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/PolarishT/sales-agent/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RagUser {
	return predicate.RagUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RagUser {
	return predicate.RagUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RagUser {
	return predicate.RagUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RagUser {
	return predicate.RagUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RagUser {
	return predicate.RagUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RagUser {
	return predicate.RagUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RagUser {
	return predicate.RagUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RagUser {
	return predicate.RagUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RagUser {
	return predicate.RagUser(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.RagUser {
	return predicate.RagUser(sql.FieldEQ(FieldUserID, v))
}

// FirstSeenAt applies equality check predicate on the "first_seen_at" field. It's identical to FirstSeenAtEQ.
func FirstSeenAt(v time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldEQ(FieldFirstSeenAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldEQ(FieldLastSeenAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.RagUser {
	return predicate.RagUser(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.RagUser {
	return predicate.RagUser(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.RagUser {
	return predicate.RagUser(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.RagUser {
	return predicate.RagUser(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.RagUser {
	return predicate.RagUser(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.RagUser {
	return predicate.RagUser(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.RagUser {
	return predicate.RagUser(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.RagUser {
	return predicate.RagUser(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.RagUser {
	return predicate.RagUser(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.RagUser {
	return predicate.RagUser(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.RagUser {
	return predicate.RagUser(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.RagUser {
	return predicate.RagUser(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.RagUser {
	return predicate.RagUser(sql.FieldContainsFold(FieldUserID, v))
}

// FirstSeenAtEQ applies the EQ predicate on the "first_seen_at" field.
func FirstSeenAtEQ(v time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtNEQ applies the NEQ predicate on the "first_seen_at" field.
func FirstSeenAtNEQ(v time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldNEQ(FieldFirstSeenAt, v))
}

// FirstSeenAtIn applies the In predicate on the "first_seen_at" field.
func FirstSeenAtIn(vs ...time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtNotIn applies the NotIn predicate on the "first_seen_at" field.
func FirstSeenAtNotIn(vs ...time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldNotIn(FieldFirstSeenAt, vs...))
}

// FirstSeenAtGT applies the GT predicate on the "first_seen_at" field.
func FirstSeenAtGT(v time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldGT(FieldFirstSeenAt, v))
}

// FirstSeenAtGTE applies the GTE predicate on the "first_seen_at" field.
func FirstSeenAtGTE(v time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldGTE(FieldFirstSeenAt, v))
}

// FirstSeenAtLT applies the LT predicate on the "first_seen_at" field.
func FirstSeenAtLT(v time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldLT(FieldFirstSeenAt, v))
}

// FirstSeenAtLTE applies the LTE predicate on the "first_seen_at" field.
func FirstSeenAtLTE(v time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldLTE(FieldFirstSeenAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.RagUser {
	return predicate.RagUser(sql.FieldLTE(FieldLastSeenAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RagUser) predicate.RagUser {
	return predicate.RagUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RagUser) predicate.RagUser {
	return predicate.RagUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RagUser) predicate.RagUser {
	return predicate.RagUser(sql.NotPredicates(p))
}
